### ISSUE TITLE
transaction error occurs when I restore the rqlite

### ISSUE THREAD

**Issue by arstercz** [rqlite/rqlite#382] opened 2017-11-24 08:27 UTC
env:
```
os: centos 6.5
kernel: 2.6.32-431.3.1.el6.x86_64
rqlited: 4.2.0
```

the `rqlited` was compiled from source code:
```
build:
  build_time: 2017-11-20T10:08:20+0000
  commit: 81d44a2319cfad2f1889014d0362cb1c8006f589
  version: 4.2.0
  branch: master
```

I backup the data with following command:
```
curl localhost:4001/db/backup -o bak.sqlite3
```

there is no response when I backup from the followers, only the leader of the cluster is backup ok. and the following error occurs when I restore data:
```
# echo ".dump" | sqlite3 bak.sqlite3 > restore.dump
# curl -XPOST localhost:4001/db/load -H "Content-type: text/plain" --data-binary @restore.dump  
{"results":[{"error":"cannot start a transaction within a transaction"}]}
```
restore.dump content:
```
# cat restore.dump 
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT);
INSERT INTO "foo" VALUES(1,'fiona');
INSERT INTO "foo" VALUES(2,'fiona2222');
INSERT INTO "foo" VALUES(4,'cztest');
INSERT INTO "foo" VALUES(5,'cztest7');
COMMIT;
```
I notice the `.status` message:
```
  sqlite3:
    dns: 
    fk_constraints: disabled
    path: :memory:
    version: 3.17.0
```

my system version is **sqlite-3.6.20-1.el6_7.2.x86_64**, is the version to low?  and when I restore with **centos7, sqlite-3.7.17-4.el7.x86_64**, there is no errors, all is ok, the `3.7.17` version is also below `3.17.0`, the same question is only restore to leader is ok.

**Comment by arstercz** [comment] 2017-11-24 08:40
restore with `sqlite3` command on centos 6.5 is ok:
```
# sqlite3 ttt <./restore.dump
# sqlite3 ttt 'select * from foo limit 2'        
1|fiona
2|fiona2222
```

**Comment by otoolep** [comment] 2017-11-24 15:46
Thanks for your report. I just tried loading the dump file you supplied and cannot reproduce any problem. I am building top-of-tree on Ubuntu 16.10.

```
~ $ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=SELECT * FROM foo'
{
    "results": [
        {
            "error": "no such table: foo"
        }
    ],
    "time": 0.000195412
}
~ $ cat b.dump 
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT);
INSERT INTO "foo" VALUES(1,'fiona');
INSERT INTO "foo" VALUES(2,'fiona2222');
INSERT INTO "foo" VALUES(4,'cztest');
INSERT INTO "foo" VALUES(5,'cztest7');
COMMIT;
~ $ curl -XPOST localhost:4001/db/load -H "Content-type: text/plain" --data-binary @b.dump
{"results":[{"last_insert_id":5,"rows_affected":1}]}~ $ 
~ $ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=SELECT * FROM foo'
{
    "results": [
        {
            "columns": [
                "id",
                "name"
            ],
            "types": [
                "integer",
                "text"
            ],
            "values": [
                [
                    1,
                    "fiona"
                ],
                [
                    2,
                    "fiona2222"
                ],
                [
                    4,
                    "cztest"
                ],
                [
                    5,
                    "cztest7"
                ]
            ],
            "time": 0.000106901
        }
    ],
    "time": 0.000134945
}
```
The sqlite details are as follows:
```
  sqlite3:
    dns: 
    fk_constraints: disabled
    path: :memory:
    version: 3.21.0
```
Are you sure you're not generating any other queries to the system during the restore? Does it fail with a single node?

Did you first delete all data in the system before restoring? You must do this to be sure it works, as per https://github.com/rqlite/rqlite/blob/master/DOC/RESTORE_FROM_SQLITE.md#caveats

**Comment by otoolep** [comment] 2017-11-24 15:49
To delete all data, shutdown the cluster and delete the data directory each node uses. Then restart the cluster.

**Comment by arstercz** [comment] 2017-11-25 01:02
hi @otoolep , it's ok to restore the table when I shutdown the cluster and delete the data directory echo node uses.
and I found an interesting phenomenon, wen can reproduce the error when we use the following steps:
1. just delete the table rows in the cluster:
```
localhost:4001> delete from foo;
4 rows affected (0.000000 sec)
```
2. `table foo already exists`` error occurs when to restore:
```
# curl -XPOST localhost:4001/db/load -H "Content-type: text/plain" --data-binary @restore.dump
{"results":[{"error":"table foo already exists"}]}
```
3. then I drop the `foo` table in the cluster:
```
localhost:4001> drop table foo;
4 rows affected (0.000000 sec)
```
4. the error occurs when to restore:
```
# curl -XPOST localhost:4001/db/load -H "Content-type: text/plain" --data-binary @restore.dump
{"results":[{"error":"cannot start a transaction within a transaction"}]}
```

I think the error `cannot start a transaction within a transaction`  is because the `step 2` start a transaction, and does not commit or rollback when the `table foo already exists` occured. so I execute `commit` in the cluster:
```
localhost:4001> commit;
0 row affected (0.000000 sec)
```
and the restore is ok:
```
# curl -XPOST localhost:4001/db/load -H "Content-type: text/plain" --data-binary @restore.dump
{"results":[{"last_insert_id":5,"rows_affected":1}]}
```

**Comment by otoolep** [comment] 2017-11-25 01:26
Thank you @arstercz -- that is odd. I will look into why that is, it may be a bug in rqlite.

**Comment by otoolep** [comment] 2017-11-25 01:35
OK, I agree with your analysis -- the dump file starts a transaction, but doesn't roll it back in the event of an error. I would say, strictly speaking, that you're not clearing out the system fully before restoring though, so you're getting the "undefined" behavior I did warn about.

But I do think I can make the system more robust.

**Comment by otoolep** [comment] 2017-11-25 01:49
By more robust, I mean have it fully cleanup the transaction if the the restore operation fails, but ultimately it's best to remove all data under the system before doing a restore.

**Comment by arstercz** [comment] 2017-11-25 11:08
thanks @otoolep ,  it's best to rwmove all data before restore, and it would be better if the system more robust

**Comment by otoolep** [comment] 2017-11-25 22:40
Closing in favour of https://github.com/rqlite/rqlite/issues/385

**Closed by otoolep** 2017-11-25 22:40 UTC
