### ISSUE TITLE
Resuming instance from different network address with existing raft.db triggers unnecessary election and fails to join

### ISSUE THREAD

**Issue by brennantaylor** [rqlite/rqlite#818] opened 2021-06-16 18:57 UTC
**What version are you running?**
Tested 5.9.0 and 6.0.0 on OSX. Was also having the same issues with the `rqlite/rqlite:6.0.0` docker image.

**What did you do?**
Started 3 rqlited's locally on different ports to form a 3 proc cluster, say node-ids `rqlite-0`, `rqlite-1` and `rqlite-2`.

My intent was to remove rqlite-0 running on port 4001+4002 and re-add it on another port, say 4007+4008 to simulate a different network address like one may find when pods migrate around in Kubernetes.

**What did you expect to happen?**

When rejoining the cluster by either using the network addresses inside the existing raft log or by using the new `-join` params provided it would connect to the other members and catch its log up to the latest point and continue along its merry way at the new network addresses without needing to replicate the entire raft log.

**What happened instead?**

No matter what I tried it would try to trigger a new vote that the other nodes would reject because there was already a healthy leader.

The only way to get it to rejoin was by wiping out the `raft.db` for that process and having it join fresh.

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**

Start 3 rqlited's. Have the 2nd and 3rd join the first to form the cluster.

```
$ rqlited -node-id=rqlite-0 -http-addr=localhost:4001 -raft-addr=localhost:4002 0
$ rqlited -node-id=rqlite-1 -http-addr=localhost:4003 -raft-addr=localhost:4004 -join localhost:4001 1
$ rqlited -node-id=rqlite-2 -http-addr=localhost:4005 -raft-addr=localhost:4006 -join localhost:4001 2
```

Check cluster state:

```
$ curl "http://localhost:4003/nodes?pretty"
{
    "rqlite-0": {
        "api_addr": "http://localhost:4001",
        "addr": "127.0.0.1:4002",
        "reachable": true,
        "leader": true
    },
    "rqlite-1": {
        "api_addr": "http://localhost:4003",
        "addr": "127.0.0.1:4004",
        "reachable": true,
        "leader": false
    },
    "rqlite-2": {
        "api_addr": "http://localhost:4005",
        "addr": "127.0.0.1:4006",
        "reachable": true,
        "leader": false
    }
}
```

Kill rqlite-0 and check to see that the leader has moved.

```
$ curl "http://localhost:4003/nodes?pretty"
{
    "rqlite-0": {
        "addr": "127.0.0.1:4002",
        "reachable": false,
        "leader": false
    },
    "rqlite-1": {
        "api_addr": "http://localhost:4003",
        "addr": "127.0.0.1:4004",
        "reachable": true,
        "leader": false
    },
    "rqlite-2": {
        "api_addr": "http://localhost:4005",
        "addr": "127.0.0.1:4006",
        "reachable": true,
        "leader": true
    }
}
```

Remove rqlite-0 from the cluster

```
$ MASTER=$(curl -s "http://localhost:4001/nodes" "http://localhost:4003/nodes" "http://localhost:4005/nodes" | jq -r '.[] | select(.leader==true) | .api_addr' | head -n 1)
$ curl -XDELETE -Lv $MASTER/remove -d "{\"id\": \"rqlite-0\"}"
```

Check cluster state:

```
$ curl "http://localhost:4003/nodes?pretty"
{
  "rqlite-1": {
    "api_addr": "http://localhost:4003",
    "addr": "127.0.0.1:4004",
    "reachable": true,
    "leader": false
  },
  "rqlite-2": {
    "api_addr": "http://localhost:4005",
    "addr": "127.0.0.1:4006",
    "reachable": true,
    "leader": true
  }
}
```

Restart rqlite-0 and you'll see that it tries to trigger a vote forever

```
[rqlited] 2021/06/16 10:11:48 rqlited starting, version 6, commit unknown, branch unknown
[rqlited] 2021/06/16 10:11:48 go1.16.3, target architecture is amd64, operating system target is darwin
[rqlited] 2021/06/16 10:11:48 launch command: rqlited -node-id=rqlite-0 -http-addr=localhost:4001 -raft-addr=localhost:4002 0
[mux] 2021/06/16 10:11:48 received handler registration request for header 1
[mux] 2021/06/16 10:11:48 received handler registration request for header 2
[cluster] 2021/06/16 10:11:48 service listening on 127.0.0.1:4002
[mux] 2021/06/16 10:11:48 mux serving on 127.0.0.1:4002, advertising 127.0.0.1:4002
[rqlited] 2021/06/16 10:11:48 preexisting node state detected in /Users/brentaylor/rqlite-data/0
[rqlited] 2021/06/16 10:11:48 no join addresses set
[store] 2021/06/16 10:11:48 opening store with node ID rqlite-0
[store] 2021/06/16 10:11:48 ensuring directory at /Users/brentaylor/rqlite-data/0 exists
[store] 2021/06/16 10:11:48 0 preexisting snapshots present
[store] 2021/06/16 10:11:48 first log index: 1, last log index: 4, last command log index: 0:
2021-06-16T10:11:48.141-0700 [INFO]  raft: initial configuration: index=4 servers="[{Suffrage:Voter ID:rqlite-0 Address:127.0.0.1:4002} {Suffrage:Voter ID:rqlite-1 Address:127.0.0.1:4004} {Suffrage:Voter ID:rqlite-2 Address:127.0.0.1:4006}]"
[store] 2021/06/16 10:11:48 no cluster bootstrap requested
2021-06-16T10:11:48.141-0700 [INFO]  raft: entering follower state: follower="Node at 127.0.0.1:4002 [Follower]" leader=
2021-06-16T10:11:50.046-0700 [WARN]  raft: heartbeat timeout reached, starting election: last-leader=
2021-06-16T10:11:50.046-0700 [INFO]  raft: entering candidate state: node="Node at 127.0.0.1:4002 [Candidate]" term=3
2021-06-16T10:11:50.239-0700 [INFO]  raft: entering follower state: follower="Node at 127.0.0.1:4002 [Follower]" leader=
2021-06-16T10:11:52.016-0700 [WARN]  raft: heartbeat timeout reached, starting election: last-leader=
2021-06-16T10:11:52.016-0700 [INFO]  raft: entering candidate state: node="Node at 127.0.0.1:4002 [Candidate]" term=5
2021-06-16T10:11:53.850-0700 [WARN]  raft: Election timeout reached, restarting election
2021-06-16T10:11:53.850-0700 [INFO]  raft: entering candidate state: node="Node at 127.0.0.1:4002 [Candidate]" term=6
2021-06-16T10:11:55.282-0700 [WARN]  raft: Election timeout reached, restarting election
2021-06-16T10:11:55.282-0700 [INFO]  raft: entering candidate state: node="Node at 127.0.0.1:4002 [Candidate]" term=7
... etc etc
[rqlited] 2021/06/16 10:13:48 leader did not appear within timeout: timeout expired
```

And the other nodes will reject the request for a vote since a leader is
already present and healthy

```
2021-06-16T10:13:15.361-0700 [WARN]  raft: rejecting vote request since we have a leader: from=127.0.0.1:4002 leader=127.0.0.1:4006
```

Kill all the rqlited's and delete the raft state on disk. Restart the cluster
fresh. Once cluster is formed kill rqlite-0, remove the node and start it on
new ports and tell it to join the others:

```
$ MASTER=$(curl -s "http://localhost:4001/nodes" "http://localhost:4003/nodes" "http://localhost:4005/nodes" | jq -r '.[] | select(.leader==true) | .api_addr' | head -n 1)
$ curl -XDELETE -Lv $MASTER/remove -d "{\"id\": \"rqlite-0\"}"
rqlited -node-id=rqlite-0 -http-addr=localhost:4007 -raft-addr=localhost:4008 -join localhost:4003,localhost:4005 0
```

The same thing happens as before where rqlite-0 triggers a vote and the others
reject. Eventually rqlite-0 fails. The other nodes never consider it joined.

```
$ curl "http://localhost:4003/nodes?pretty"
{
  "rqlite-1": {
    "api_addr": "http://localhost:4003",
    "addr": "127.0.0.1:4004",
    "reachable": true,
    "leader": true
  },
  "rqlite-2": {
    "api_addr": "http://localhost:4005",
    "addr": "127.0.0.1:4006",
    "reachable": true,
    "leader": false
  }
}
```

If we remove rqlite-0's state it can rejoin at the new address without issue and it just replicates the raft log from the other members. This does not require the node to be removed, it gets replaced properly.

```
$ rm -rf 0
rqlited -node-id=rqlite-0 -http-addr=localhost:4007 -raft-addr=localhost:4008 -join localhost:4003,localhost:4005 0
[rqlited] 2021/06/16 10:28:04 rqlited starting, version 6, commit unknown, branch unknown
[rqlited] 2021/06/16 10:28:04 go1.16.3, target architecture is amd64, operating system target is darwin
[rqlited] 2021/06/16 10:28:04 launch command: rqlited -node-id=rqlite-0 -http-addr=localhost:4007 -raft-addr=localhost:4008 -join localhost:4003,localhost:4005 0
[mux] 2021/06/16 10:28:04 received handler registration request for header 1
[mux] 2021/06/16 10:28:04 received handler registration request for header 2
[cluster] 2021/06/16 10:28:04 service listening on 127.0.0.1:4008
[mux] 2021/06/16 10:28:04 mux serving on 127.0.0.1:4008, advertising 127.0.0.1:4008
[rqlited] 2021/06/16 10:28:04 no preexisting node state detected in /Users/brentaylor/rqlite-data/0, node may be bootstrapping
[rqlited] 2021/06/16 10:28:04 join addresses specified, node is not bootstrapping
[store] 2021/06/16 10:28:04 opening store with node ID rqlite-0
[store] 2021/06/16 10:28:04 ensuring directory at /Users/brentaylor/rqlite-data/0 exists
[store] 2021/06/16 10:28:04 0 preexisting snapshots present
[store] 2021/06/16 10:28:04 first log index: 0, last log index: 0, last command log index: 0:
2021-06-16T10:28:04.534-0700 [INFO]  raft: initial configuration: index=0 servers=[]
[store] 2021/06/16 10:28:04 no cluster bootstrap requested
[rqlited] 2021/06/16 10:28:04 join addresses are: [localhost:4003 localhost:4005]
2021-06-16T10:28:04.534-0700 [INFO]  raft: entering follower state: follower="Node at 127.0.0.1:4008 [Follower]" leader=
[rqlited] 2021/06/16 10:28:04 successfully joined cluster at http://localhost:4003/join
2021-06-16T10:28:04.675-0700 [WARN]  raft: failed to get previous log: previous-index=7 last-index=0 error="log not found"
[store] 2021/06/16 10:28:04 waiting for up to 2m0s for application of initial logs
[rqlited] 2021/06/16 10:28:04 store has reached consensus
[http] 2021/06/16 10:28:04 service listening on 127.0.0.1:4007
[rqlited] 2021/06/16 10:28:04 node is ready
```

**Comment by otoolep** [comment] 2021-06-17 17:15
Thanks for your report. Due to personal committments I may not be able to look at this for 1-2 weeks.

**Comment by otoolep** [comment] 2021-06-24 12:50
OK, I read your issue. Hashicorp Raft doesn't work like that AFAIK. If you explicitly remove the node, you must also remove the data directory. Removing node means just that -- it's completely removed, and if you start it up with any preexisting state, it won't just become part of the cluster and use the state underneath.

I believe the best to think about this is one you remove the node, you should consider it gone. You can't decide to use it again. Don't think of a node "changing network addresses" -- instead think of adding a new node at the network address.

I'm interested in making rqlite work better with Kubernetes. If you can provide examples of clustered systems working in the manner you wish with Kubernetes, I'd be interested in studying them. But the behaviour you are seeing is the Hashicorp system -- the same one that powers Consul.

**Comment by otoolep** [comment] 2021-06-24 12:51
Closing, but re-open if I am missing something.

**Comment by brennantaylor** [comment] 2021-06-25 22:55
Oh I slimmed down my original report a bit so it looks like I failed to communicate that something the docs say should be possible I couldn't get working.

What I meant was that I can't get a node to rejoin the cluster on a new network address without wiping its state.

These docs seem to imply its as simple as just passing `-join`: https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#modifying-a-nodes-network-addresses

If it is required that one needs to wipe the data maybe the docs need an update?

But that raises more questions around "disaster recovery".

In the scenario where all the processes die and the ip addresses rotate (maybe they were spot instances and they all died at the same time, this isn't k8s specific) how does a bootstrap occur? I guess bring 1 up, restore from backup then form the cluster?

Looking at the bitnami charts they execute a `consul leave` when the process is stopping https://github.com/bitnami/charts/blob/master/bitnami/consul/templates/statefulset.yaml#L213

The [consul leave](https://www.consul.io/commands/leave) docs state:

> For nodes in server mode, the node is removed from the Raft peer set in a graceful manner. This is critical, as in certain situations a non-graceful leave can affect cluster availability.

I'd need to do some testing to see if it behaves gracefully and rejoins gracefully as expected.

Since this is modeled on the hashicorp raft library maybe seeing how consul operates on k8s is work investigating 🤷

**Comment by otoolep** [comment] 2021-06-26 14:21
@brennantaylor -- thanks for pointing that out in the docs. Either the docs have always been wrong (which wouldn't be good) or there is a regression in the code (not good either). Re-opening this issue, as something is clearly wrong.

**Comment by otoolep** [comment] 2021-06-26 14:54
So there appears to be a confusion in my docs, I think this has been a long running issue. I'm interested in your opinion on this topic @brennantaylor 

Statement 1, from https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#creating-a-cluster:

_In fact, if a node is already a member of a cluster (even if the cluster is just that node) -join is then ignored._

Statement 2, from https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#modifying-a-nodes-network-addresses:

_Simply pass the new address on the command line. You must also, however, explicitly tell the node to join the cluster again, by passing -join to the node._

So Statement 1 is what you're seeing -- `-join` is actually ignored is the "...a member of a cluster". Having state on disk is the definition of "member of a cluster", so blowing away the state means `-join` is obeyed again.

The system works like this because I wanted folks not to have to worry about removing `-join` from their command lines on subsequent restarts of a node. Quote:

_This can be convenient because it means join requests are idempotent, allowing you to leave the initial command-line parameters unchanged, including any `-join` options._

Perhaps this mode of operation hurts more than it helps?

**Comment by otoolep** [comment] 2021-06-26 14:57
I'd need to dig into the system to see what happens if `-join` is always obeyed, even if there is preexisting state on disk. It may actually be OK. And perhaps there are simple ways for systems to be restarted automatically, but not pass join except for the first time.

By the way, your reference to the "leave" command. That sounds reasonable, but in the real world my assumption is one could always lose a node in non-graceful manner, and not get a chance to execute leave (a datacenter-wide power cut for example, where *everything* goes down). So it isn't bulletproof, right?

**Comment by otoolep** [comment] 2021-06-26 15:17
The change to make the system work the way you expected is quite simple: https://github.com/rqlite/rqlite/pull/822

If the system worked like this, would it address your disaster-recovery scenario? I'm definitely tempted to make this change, but it could have unintended consequences for others. But ultimately it may not matter since actually re-joining is not the end of the world, the existing "ignore the join if member of cluster" code may be trying to avoid a problem that doesn't exist in practise.

**Comment by otoolep** [comment] 2021-06-26 15:38
More I think about this, I think it's the right change. I believe I had rqlite ignore join requests if a node was already a member of a cluster, as I wanted to avoid folks telling a node, with pre-existing state, to join the wrong cluster. But this is not really a meaningful thing to do, clearly a mistake, and something folks won't do in practise. It may be better to just state that trying to do this is wrong (obviously), and that the behaviour is undefined.

If folks do pass `-join` to a node with pre-existing state, and the node attempts to re-join a cluster it's already a member of, it's not the end of the world. In fact if nothing about the node has changed -- if its node ID and Raft address are actually the same, the cluster ignores the join request -- see https://github.com/rqlite/rqlite/blob/v6.0.0/store/store.go#L698.

So in that sense `-join` is idempotent and is effectively ignored by the cluster as a whole.

If either the Raft address or node ID has changed -- the former being your case -- the cluster removes the node first, and then processes the Join request -- see https://github.com/rqlite/rqlite/blob/v6.0.0/store/store.go#L705. This behavior has been in plac for a over a year now, so that code isn't new.

The biggest question is what happens if a node goes down, some changes happen to the cluster, and then the node comes back up with a new, say, Raft address. It will have existing state, but will behind the cluster. In that case I'm not actually sure how the Hashicorp system handles it -- I would need to look into the code, and run some tests. It may or may not replay the entire log, or it may just send the changes that were missed by the node while it was down.

But in summary I believe changing the system to operate the way you want may be the right thing to do after all. Some further testing should ensure it'll all work fine.

**Comment by otoolep** [comment] 2021-06-26 16:01
>>In the scenario where all the processes die and the ip addresses rotate (maybe they were spot instances and they all died at the same time, this isn't k8s specific) how does a bootstrap occur? I guess bring 1 up, restore from backup then form the cluster?

Thinking a bit more, this is a complete cluster loss, and rebuilding and restoring from backup is required (unless each spot instance was using persistent disk and you could just restart them with the same network addresses -- or at least one of nodes with the same network address, I think).

While I still think the changed proposed to address this issue is a good one (it will allow one to change node addresses easily), it doesn't really help with a complete cluster loss. Agreed?

**Comment by otoolep** [comment] 2021-06-28 15:16
Fixed in 6.0.1. Thanks for your helpful report @brennantaylor.

**Closed by otoolep** 2021-06-28 15:16 UTC

**Comment by brennantaylor** [comment] 2021-06-28 18:06
Sorry I missed this over the weekend and thanks so much for indulging me.

Just finished reading what you wrote and super happy to see the change. I'll retest it this afternoon and see what happens. If all goes well locally I'll run it in my k8s sandbox and see what I can do.

Some thoughts:
- Indeed I am using persistent disks so in the case of a full cluster loss I'd hope it would be possible to bring things back online from disk state. I believe this is one reason consul has the `bootstrap_expect` option to say "Oh hey don't let writes happen until this many nodes join and reconcile". So that would give the cluster time to come up and see "who has the latest version of the log".
- In k8s land I would use a `Service` to load balance to other healthy members of the cluster. So outside the initial bootstrap I'd be happy just always passing `-join http://loadbalancedname:4001`.

**Comment by otoolep** [comment] 2021-06-28 18:36
Yeah, this change should allow you to pass `-join` to any node, at any time, and everything should just work -- even if the network addresses change. So I believe 6.0.1 should be an improvement all round, and make it easier to run clusters in practise.

**Comment by brennantaylor** [comment] 2021-07-01 02:22
I did retest and it worked as expected for my localhost cases. IE I can restart rqlite-0 and have it rejoin at a new address.

**Comment by brennantaylor** [comment] 2021-07-01 02:27
IIRC consul has an internal randomly generated `cluster id` to prevent cross wiring a join to a different cluster.

**Comment by paulosotu** [comment] 2021-09-15 22:55
Hey @otoolep and @brennantaylor,

Was just hitting this exact issue. I have a microk8 3 node home cluster and was setting up rqlite to run on a statfulset. I actually force evicted all the pods of the cluster forcing k8's to re-schedule it. All pods are re-schedule with the same persistent disk that provides the exact same state. The problem here is that because we don't have a leader all join requests get ignored meaning the cluster will never recover ...

I see in the log:
```
(...)
[store] 2021/09/15 22:02:07 received request from node with ID rqlite-statefulset-1, at 10.1.157.149:4002, to join this node
(...)
 [ERROR] raft: failed to make requestVote RPC: target="{Voter rqlite-statefulset-1 10.1.157.145:4002}" error="dial tcp 10.1.157.145:4002: i/o timeout
```
 My question here since I'm using the node id is what would be the consequence of updating the  rqlite-statefulset-1 ip address when receiving the join request with the updated IP even when no leader exists? 
At the moment it simply returns a 503 due to the protection on store/store.go:
```
(...)
if s.raft.State() != raft.Leader {
		return ErrNotLeader
	}
(...)
```

**Comment by otoolep** [comment] 2021-09-15 23:07
@paulosotu -- what version are you running?

**Comment by paulosotu** [comment] 2021-09-16 07:27
Hey @otoolep, made a new docker image out of the code from the master branch ( running with some raspberry nodes so needed a arm64 binary)

**Comment by otoolep** [comment] 2021-09-16 10:53
I'm not quite following. But when no leader exists, the cluster isn't functional, I'm not sure what is going to happen.

Can you provide step-by-step reproduction instructions for the issue you are seeing?

**Comment by paulosotu** [comment] 2021-09-16 14:27
Basically made a Statefulset with 3 replicas to create a 3 node raft cluster. Gave a unique id for each as the pod name, that will always be the same for that specific pode.  Than I basically delete the statefulset to force the pods termination and add it again so they get re-scheduled (simulating the situation of one of my k8 node goes down and all of the 3 pods are living in it). 

Being a k8 statefulset they all get the same persistent volumes, state and the same pod name (used as id for raft node) . 

The issue here is with the  new rescheduling of the pods the ip addresses are different for the same node id cluster members, and because there isn't any valid leader, there is no way to associate the new ip´s to each cluster member, although they persisted their id's.

**Comment by otoolep** [comment] 2021-09-16 16:37
Ah, I see -- it's a bootstrapping issue. IP addresses have changed on all nodes, so nodes can't contact one another, so can't elect a leader. But leader is needed to officially change the IP addresses of each node.

I don't have an immediate answer, not without going into the configuration and changing it by hand (I have not done this ever). The Raft code is exactly the same as that running inside Hashicorp Consul. I wonder if that documentation discusses this scenario.

**Comment by otoolep** [comment] 2021-09-16 16:40
Sounds like the same thing here:

https://stackoverflow.com/questions/54915806/how-does-consul-recover-from-losing-quorum-with-changing-node-ips

**Comment by otoolep** [comment] 2021-09-16 16:50
Seems like Consul used to have this problem too:
http://man.hubwiz.com/docset/Consul.docset/Contents/Resources/Documents/docs/guides/consul-containers.html#known-issues

(First issue listed)

So perhaps there is something I can here, but Consul may be relying on functionality in addition to the Raft library, which both rqlite and Consul share.

**Comment by paulosotu** [comment] 2021-09-16 17:20
Yes I did find a interesting discussion back in 2017 about it:
https://github.com/hashicorp/consul/issues/1580
Went through (diagonally) through raft go library and there doesn't seem to have a easy solution without changing the lib, guess I need to dig down a bit more on consul to understand how they overcome this...

**Comment by otoolep** [comment] 2021-09-16 17:22
Actually, I wonder if this is the process:

https://learn.hashicorp.com/tutorials/consul/recovery-outage#manual-recovery-using-peers-json

I will need to test this myself very soon, unless you get to it. :-)

**Comment by paulosotu** [comment] 2021-09-16 17:22
:) nice is the same issue you mentioned on the docs you shared :)

**Comment by otoolep** [comment] 2021-09-16 17:25
rqlite uses protocol version 3.

**Comment by otoolep** [comment] 2021-09-16 18:11
OK, rqlite needs changes to fix this -- but it looks hopeful. I found the code in Consul that I *think* does recovery: https://github.com/hashicorp/consul/blob/5b6d96d27d80dbff40073e9775f2a2c187cc90c4/agent/consul/server.go#L762

I need to call this function:

https://pkg.go.dev/github.com/hashicorp/raft#ReadConfigJSON

in rqlite.

This will take a little bit of work, but I suspect it's doable. Let me get back to you.

**Comment by otoolep** [comment] 2021-09-17 01:13
@paulosotu -- I'm pretty sure I can fix this, and allow you to restart clusters even if every IP address is different. It's going to take a few days to code it up. Follow https://github.com/rqlite/rqlite/issues/897 for more details.

**Comment by paulosotu** [comment] 2021-09-17 07:57
Cool :) thanks will follow up on the development 👍

**Comment by otoolep** [comment] 2021-09-21 03:23
@paulosotu -- you stated you build from HEAD. HEAD should support what you need now, full directions here:

https://github.com/rqlite/rqlite/blob/master/DOC/CLUSTER_MGMT.md#recovering-a-cluster-that-has-permanently-lost-quorum

Can you try it, and let me know how it goes? If it looks good to you, I can make a new release.

**Comment by paulosotu** [comment] 2021-09-21 08:09
Wow cool, Will try it  during today and let you know.

**Comment by paulosotu** [comment] 2021-09-21 11:20
Done some tests and all seem to be working as documented :) adding the peers.json the cluster recovers correctly and healthy. Thanks @otoolep 👍

**Comment by paulosotu** [comment] 2022-01-13 18:49
@otoolep just in case someone gets into this thread built a medium article on how to have rqlite running on a microk8 cluster recovering automatically from pod scheduling:
https://medium.com/@mr.pauloferreira/how-to-setup-a-usable-rqlite-cluster-with-3-node-microk8-multi-architecture-cluster-7c27c1c1edf7

Thanks again mate :)

**Comment by otoolep** [comment] 2022-01-13 18:56
@paulosotu -- thanks. Can you drop me an email? My address is in my profile. I'm working on better, automatic clustering for rqlite, and would like to know if I'm on the right path. My goal is make rqlite super-easy to cluster with the help of Consul, etcd, or Kubernetes. I'd like to understand your use case more, if you're up for chatting.

You can find the PR for etcd and consul here: https://github.com/rqlite/rqlite/pull/957

With this functionality you pass the address of a Consul (for example) server to every rqlite node, and the nodes automatically cluster together. With this functionality in place, a 3-node rqlite cluster can be launched as follows:
```bash
rqlited -node-id 1 -http-addr 10.0.0.1:4001 -raft-addr 10.0.0.1:4002 -disco-mode=consul data
rqlited -node-id 2 -http-addr 10.0.0.2:4001 -raft-addr 10.0.0.2:4002 -disco-mode=consul data
rqlited -node-id 3 -http-addr 10.0.0.3:4001 -raft-addr 10.0.0.3:4002 -disco-mode=consul data
```
Furthermore, additional nodes can be launched afterwards, and by pointing them at the same Consul server, they will find the current leader (even if it changes during the life of the cluster) and join the cluster. 

I'd like to understand how to do the same thing for Kubernetes -- what would be the best pattern?
