### ISSUE TITLE
The HTTP API does not redirect the 'q' part of a GET sent to a non-leader node

### ISSUE THREAD

**Issue by jack-y** [rqlite/rqlite#329] opened 2017-07-24 09:35 UTC
As the doc says: 

> You can connect the CLI to any node in the cluster, and it will automatically forward its requests to the leader.

But the HTTP API does not have the same behavior:

- a GET request to the leader is OK
- the same GET request to a non-leader node returns:
`<a href="http://leader-host:leader-port/db/query">Moved Permanently</a>.`

Is this the expected behavior?
It would be better to silently redirect all the request to the leader and return the result.

To reproduce:

1. Install rqlite on 2 servers: serverleader and serverfoo

2. Start a leader node on serverleader: 
```
rqlited -http-addr serverleader:4001 -raft-addr serverleader:4002 ~/node
```

3. Start another node on serverfoo: 
```
rqlited -http-addr serverfoo:4001 -raft-addr serverfoo:4002 -join http://serverleader:4001 ~/node
```

4. Create a table an insert data:
```
$ rqlite -H serverfoo -p 4001
serverfoo:4001> create table foo (id integer not null primary key, name text)
serverfoo:4001> insert into foo (1, "fiona")
serverfoo:4001> exit
```

5. Send a GET to serverleader. The result is OK:
```
curl -G "http://serverleader:4001/db/query?q=select%20*%20from%20foo"
```
`{"results":[{"columns":["id","name"],"types":["integer","text"],"values":[[1,"fiona"]]}]}`

6. Send the same GET to serverfoo:
```
curl -G "http://serverfoo:4001/db/query?q=select%20*%20from%20foo"
```
`<a href="http://serverleader:4001/db/query">Moved Permanently</a>.`

Otherwise, rqlite is awesome!

**Comment by otoolep** [comment] 2017-07-24 09:58
Thanks for your feedback @jack-y. What you are seeing is by design, so that clients have full control.

>But the HTTP API does not have the same behavior:

This is how the CLI redirects. it *uses* the response from the HTTP API indicating where the leader is.  This is the same way browsers follow redirects.

It is up to clients to follow the redirects.  For example, here is the Python client following redirects:

https://github.com/rqlite/pyrqlite/blob/master/src/pyrqlite/connections.py#L64

It would be possible to do as you say, and make it more transparent to clients, but I have chosen not to have rqlite do so at this time.

**Comment by otoolep** [comment] 2017-07-24 09:58
I am closing this for now, since this is by design.

**Closed by otoolep** 2017-07-24 09:58 UTC

**Comment by otoolep** [comment] 2017-07-24 10:02
https://github.com/rqlite/rqlite/issues/330 tracking this change request.

**Comment by otoolep** [comment] 2017-07-24 10:21
Unless @jack-y you mean the `q` part of the query is not included in the `Location` header? This may or may not be the right thing to do (not sure) but clients can easily handle the current response. since it contains sufficient information.

**Comment by jack-y** [comment] 2017-07-24 10:45
@otoolep you're right. As you suggest, now I'm handling the redirect response in my app. Thanks!
