### ISSUE TITLE
Problems quering from other  nodes

### ISSUE THREAD

**Issue by anfho93** [rqlite/rqlite#295] opened 2017-03-17 15:31 UTC
Hi.  I'm having problems with the cluster connection, im following the steps in the documentation, and when I connect directly to the leader through rqlite cmd and execute queries everything is ok, but when i do the same thing from other nodes, the answer to all the queries is:
 ERR! unexpected end of JSON input

I thinks this is related to the recent changes made. because i use curl to make a query in a non-leader node and this is what i get:

curl -G 'localhost:4003/db/query?pretty&timings' --data-urlencode 'q=.tables'
<a href="http://localhost:4001/db/query">Moved Permanently</a>.

btw, this is my configuration :

 rqlited ./node.1
 rqlited -http localhost:4003 -raft localhost:4004 -join http://localhost:4001 ./node.2
 rqlited -http localhost:4005 -raft localhost:4006 -join http://localhost:4001 ./node.3

**This is my first step on the leader node**

$ rqlite
127.0.0.1:4001> CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT)
0 row affected (0.000668 sec)
127.0.0.1:4001> .schema
+-----------------------------------------------------------------------------+
| sql                                                                         |
+-----------------------------------------------------------------------------+
| CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT)               |
+-----------------------------------------------------------------------------+
127.0.0.1:4001> INSERT INTO foo(name) VALUES("fiona")
1 row affected (0.000080 sec)
127.0.0.1:4001> SELECT * FROM foo
+----+-------+
| id | name  |
+----+-------+
| 1  | fiona |
+----+-------+

When i try to do the same on a non-leader node, this is the answer 

$ rqlite -H localhost -p 4003
localhost:4003> .schema
ERR! unexpected end of JSON input

I tried to make a curl request and this is what i get
$ curl -G 'localhost:4003/db/query?pretty&timings' --data-urlencode 'q=select * from foo'
<a href="http://localhost:4001/db/query">Moved Permanently</a>.

**This behavior was not present on the previous releases.** I hope you can help me with this.

**Comment by otoolep** [comment] 2017-03-17 15:51
Thanks for your report.
```
curl -G 'localhost:4003/db/query?pretty&timings' --data-urlencode 'q=.tables'
Moved Permanently.
```
Sending dot-commands like `.tables` directly to the HTTP endpoint is not supported. Dot-commands are actually translated to a different query by the CLI. Check the source of the CLI for details. And otherwise what you are getting back from the node is correct -- you get a 301. Pass `-v` to `curl` to see more.

As for your other issue, I cannot reproduce it. I built the latest source on MacOX and repeated your steps of connecting to the leader, and then connecting to a different node. I also tested the latest release. It all works fine.
```
$ ./rqlite 
127.0.0.1:4001> .schema
+---------------------------------------------------------------+
| sql                                                           |
+---------------------------------------------------------------+
| CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT) |
+---------------------------------------------------------------+
127.0.0.1:4001> 
EOF (CTRL+D)
$ ./rqlite -H localhost -p 4003
localhost:4003> .schema
+---------------------------------------------------------------+
| sql                                                           |
+---------------------------------------------------------------+
| CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT) |
+---------------------------------------------------------------+
localhost:4003> 
```

**Comment by otoolep** [comment] 2017-03-17 15:52
Be sure you are running `rqlite` and `rqlited` from the same release.

**Comment by otoolep** [comment] 2017-03-17 15:58
Execute `curl localhost:4001/status?pretty` and paste your output here.

**Comment by otoolep** [comment] 2017-03-17 16:01
If I had to guess, I'd say you're not running the version of rqlited you think you're running. It almost looks like you're still running older software. The status commands will show you the version each node is running.

**Comment by anfho93** [comment] 2017-03-17 17:31
Hi, the process i follow to run the software is just clone the master branch from github, the run get -d ./... , and after that go install ./...,  
Also i have all the nodes in the same PC, running from the same rqlite binary file, but on different ports

And this is the output from all the running nodes.

host in port 4001
https://drive.google.com/open?id=0B9lwPlBmlRuAZm4tbV9GaDdZc3M
host in port 4003
https://drive.google.com/open?id=0B9lwPlBmlRuAYnlBOFM2QzkwX0k
host in port 4005
https://drive.google.com/open?id=0B9lwPlBmlRuATE5hb2RvM2JQSm8

**Comment by otoolep** [comment] 2017-03-17 17:59
Nothing looks wrong with the output. I see you are running Linux, so perhaps you can rule out something wrong with your build by running a pre-built binary. You can download v3.12.1 at https://github.com/rqlite/rqlite/releases

Follow the instructions for Linux, and show me exactly what you do. Right now I cannot repro this issue. https://gist.github.com/otoolep/80dd3ac5a53bc9ecc5acd91d45a67aa6 shows me running two v3.12.1 nodes, the nodes forming a cluster, and connecting to each node via the CLI and executing `.schema` without any trouble.

**Comment by anfho93** [comment] 2017-03-17 19:59
Looks like i have troubles with my environment and building the rqlite from source code. So went back to the 3.12.0  version and built it  again but same thing happens. 

I tried to download the latest release from https://github.com/rqlite/rqlite/releases and unfortunately the same thing happens.

I will try to run this on other computer, and i will let you know about it. Thanks for your quick answer.

**Comment by otoolep** [comment] 2017-03-17 20:45
You will need to show me as detailed a sequence of events demonstrating the problem, as I showed on the gist link above (which shows everything to be fine). As far as I can see there is nothing wrong with the software.

**Comment by anfho93** [comment] 2017-03-17 21:18
Ok i tried with a new docker  and this is the full process 

https://gist.github.com/anfho93/fa6cbed9f56a61b9201e79c1d3dfec97

**Comment by otoolep** [comment] 2017-03-17 21:26
Thanks. 

Can you please do it again, but with the prebuilt 3.12.1 release? You can download the binary and just run it without building anything.

**Comment by otoolep** [comment] 2017-03-17 21:30
I wonder if it's a Go version 1.8 thing, which you use to build it. Can you also rebuilding with Go 1.7. The prebuilt binaries are built with 1.7.1 so that is why I would like you to try them.

**Comment by anfho93** [comment] 2017-03-17 21:41
I will try to re build it with go 1.7.1 and i will let you know

**Comment by otoolep** [comment] 2017-03-17 21:49
I will see if I can repro after building with 1.8.

**Comment by otoolep** [comment] 2017-03-17 21:53
There were changes in HTTP redirect handling between 1.7 and 1.8. I had to make one change to account for it: https://github.com/rqlite/rqlite/pull/289

Perhaps there is another place that needs changing.

**Comment by otoolep** [comment] 2017-03-17 22:15
OK, I can repro this when I build the system with 1.8. I'm looking into a fix.

**Comment by anfho93** [comment] 2017-03-17 22:18
Thanks a lot.

**Comment by otoolep** [comment] 2017-03-17 22:31
@anfho93 -- I believe this is now fixed on master. Do you want to pull down the latest code on master, build with Go 1.8, and see if it works now? If so, we can close this issue.

**Comment by anfho93** [comment] 2017-03-17 22:40
Works perfectly now, thank  you  so much @otoolep

**Comment by otoolep** [comment] 2017-03-17 22:54
Thank you @anfho93 for the report -- there was a real bug here. Glad it's fixed.

**Comment by wil222** [comment] 2018-07-11 12:04
Hi,

I ran into the exact same issue. I build it from the sources using go1.9 on my Raspberry Pi 3 (ARM). I used the source code at commit 2eb02dc14235583f7ed1e7fa9d9f9a8d4e86a426 on branch master (last commit up to now).

At the end is the result of `curl localhost:4001/status?pretty`. Everything seems ok on the other nodes : http.redirect = "localhost:4001", and store.raft.state = "Follower".

I will try it with go1.8 and report later. I don't know a single thing about go, but if you have bugs everytime you try to upgrade your version without a single warning... Well I don't want to know more about it.

```
{
    "build": {
        "branch": "",
        "build_time": "",
        "commit": "",
        "version": ""
    },
    "http": {
        "addr": "127.0.0.1:4001",
        "auth": "disabled",
        "conn_idle_timeout": "1m0s",
        "conn_tx_timeout": "10s",
        "redirect": "localhost:4001"
    },
    "node": {
        "start_time": "2018-07-11T13:10:47.431260462+02:00",
        "uptime": "38m49.599303526s"
    },
    "runtime": {
        "GOARCH": "arm",
        "GOMAXPROCS": 4,
        "GOOS": "linux",
        "num_cpu": 4,
        "num_goroutine": 21,
        "version": "go1.9"
    },
    "store": {
        "addr": "127.0.0.1:4002",
        "apply_timeout": "10s",
        "conn_poll_period": "10s",
        "db_conf": {
            "DSN": "",
            "Memory": true
        },
        "dir": "/home/pi/node.1",
        "heartbeat_timeout": "1s",
        "leader": {
            "addr": "127.0.0.1:4002",
            "node_id": "localhost:4002"
        },
        "metadata": {
            "localhost:4002": {
                "api_addr": "localhost:4001"
            },
            "localhost:4004": {
                "api_addr": "localhost:4003"
            },
            "localhost:4006": {
                "api_addr": "localhost:4005"
            }
        },
        "node_id": "localhost:4002",
        "nodes": [
            {
                "id": "localhost:4002",
                "addr": "127.0.0.1:4002"
            },
            {
                "id": "localhost:4004",
                "addr": "127.0.0.1:4004"
            },
            {
                "id": "localhost:4006",
                "addr": "127.0.0.1:4006"
            }
        ],
        "raft": {
            "applied_index": "10",
            "commit_index": "10",
            "fsm_pending": "0",
            "last_contact": "0",
            "last_log_index": "10",
            "last_log_term": "12",
            "last_snapshot_index": "0",
            "last_snapshot_term": "0",
            "latest_configuration": "[{Suffrage:Voter ID:localhost:4002 Address:127.0.0.1:4002} {Suffrage:Voter ID:localhost:4004 Address:127.0.0.1:4004} {Suffrage:Voter ID:localhost:4006 Address:127.0.0.1:4006}]",
            "latest_configuration_index": "6",
            "num_peers": "2",
            "protocol_version": "3",
            "protocol_version_max": "3",
            "protocol_version_min": "0",
            "snapshot_version_max": "1",
            "snapshot_version_min": "0",
            "state": "Leader",
            "term": "12"
        },
        "snapshot_threshold": 8192,
        "sqlite3": {
            "dsn": "",
            "fk_constraints": "disabled",
            "path": ":memory:",
            "version": "3.24.0"
        }
    }
}
```

**Comment by wil222** [comment] 2018-07-11 13:39
Ok, I'm a bit confused here. I tried the following combinations and none worked :
go1.7 on ARM
go1.8 on ARM
go1.9 on ARM
go1.8 on amd64
go1.10 on amd64

All give the same result :
```
ThinkPad-E560 ~/rqlite $ ./rqlite
127.0.0.1:4001> CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT)
0 row affected (0.000000 sec)
127.0.0.1:4001>  INSERT INTO foo(name) VALUES("fiona")
1 row affected (0.000000 sec)
127.0.0.1:4001> select * from foo
+----+-------+
| id | name  |
+----+-------+
| 1  | fiona |
+----+-------+
127.0.0.1:4001> 
EOF (CTRL+D)
ThinkPad-E560 ~/rqlite $ ./rqlite -p 4003
127.0.0.1:4003> select * from foo
ERR! unexpected end of JSON input
```

I am guessing I am not compiling it the way I should, even if I am following the steps of package.sh with very few modifications :
```
REPO_URL="https://github.com/rqlite/rqlite"

VERSION=$1
RELEASE_ID=$2
API_TOKEN=$3

tmp_build=`mktemp -d`
tmp_pkg=`mktemp -d`

kernel=`uname -s`
machine=`uname -m`
if [ "$machine" == "x86_64" ]; then
    machine="amd64"
fi

mkdir -p $tmp_build/src/github.com/rqlite
export GOPATH=$tmp_build
cd $tmp_build/src/github.com/rqlite
git clone $REPO_URL
cd rqlite
go get -d ./...
branch=`git rev-parse --abbrev-ref HEAD`
commit=`git rev-parse HEAD`
kernel=`uname -s`
buildtime=`date +%Y-%m-%dT%T%z`
go install -ldflags="-X main.version=$VERSION -X main.branch=$branch -X main.commit=$commit -X main.buildtime=$buildtime" ./...
```

**Comment by wil222** [comment] 2018-07-11 15:18
Don't mind me. I got it working with v4.3.0 77e345b97c5597c1ef86e75e690539de369b8dd3
However, it means there is a bug since this version.

**Comment by otoolep** [comment] 2018-07-23 01:35
Re-opening so I take a look for 5.0.

**Comment by otoolep** [comment] 2019-01-29 01:09
little-pan@ -- I don't the problem with the code you point at. Exactly where is the reader called multiple times?

**Comment by little-pan** [comment] 2019-01-29 09:06
@otoolep The result func of makeQueryRequest() is called multiple times when the rqlited follower node returns http 302(eg. this node not the leader). And another bug(such issue also in other http api implementations) exists in following function:
```golang
// github.com/rqlite/rqlite/http/service.go handleQuery()
var resp Response
results, err := queryer.Query(&store.QueryRequest{queries, timings, isAtomic, lvl})
if err != nil {
	if err == store.ErrNotLeader {
		leader := s.leaderAPIAddr()
		if leader == "" {
			http.Error(w, err.Error(), http.StatusServiceUnavailable)
			return
		}

		// - little-pan Bug-fix: should restore the shifted path here.
		r.URL.Path = "/db/query"
		
		redirect := s.FormRedirect(r, leader)

		// - little-pan
		s.logger.Printf("query: redirect to %s", redirect)

		http.Redirect(w, r, redirect, http.StatusMovedPermanently)
		return
// ...
```
When s.FormRedirect(r, leader) called in the handleQuery() func, the r.URL.Path(has been shifted in the front handler steps) doesn't be restored to original request URL path, then as Location of http redirection. This way can lead to "ERR! unexpected end of JSON input"(status code http 400 actually), because of the Location header of http redirection has been truncated and incorrect.

**Comment by little-pan** [comment] 2019-01-29 09:17
And no such issues are in rqlite v4.4.0(http api implementation relatively simple and stable), but the redirection is a bit slow in windows 8 x86_64(no the performation issue in centos 7 x86_64).

**Comment by otoolep** [comment] 2019-01-29 12:49
OK, I'll take look when I return to the code -- thanks.

**Comment by otoolep** [comment] 2020-04-12 18:40
No known issues in 5.x.

**Closed by otoolep** 2020-04-12 18:40 UTC
