### ISSUE TITLE
Error when upgrading rqlite from version 5.4 to version 5.7 or higher

### ISSUE THREAD

**Issue by Dorsosiv** [rqlite/rqlite#723] opened 2021-01-04 09:44 UTC
Hello,
When we upgrading our rqlite we receive this error:

2020-12-31T15:24:20.292Z [INFO] raft: pipelining replication: peer="{Voter rqlite-0 10.233.96.164:4002}"
panic: failed to unmarshal execute subcommand: flate: corrupt input before offset 7
goroutine 12 [running]:
github.com/rqlite/rqlite/store.(*Store).Apply(0xc000020c60, 0xc00031e460, 0x1484000, 0xdbbee0)
/tmp/tmp.z4deDlA53o/src/github.com/rqlite/rqlite/store/store.go:859 +0x838
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0006e3e10)
/tmp/tmp.z4deDlA53o/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:90 +0x2c1
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc0006f2000, 0x3, 0x40)
/tmp/tmp.z4deDlA53o/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc0001e2000)
/tmp/tmp.z4deDlA53o/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:219 +0x42f
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0001e2000, 0xc00005faa0)
/tmp/tmp.z4deDlA53o/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
/tmp/tmp.z4deDlA53o/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:144 +0x66

Thanks in advance.

**Comment by otoolep** [comment] 2021-01-04 12:27
Thanks for the report, I'll take a look shortly. I did perform upgrade testing, perhaps I missed a case -- but this should work.. If you want to workaround this, you could backup your 5.4 node, and restore it into a completely new 5.8 node.

**Comment by otoolep** [comment] 2021-01-04 12:31
FWIW, the upgrade test are here:

https://github.com/rqlite/rqlite/blob/master/store/store_test.go#L1108
https://github.com/rqlite/rqlite/blob/master/system_test/single_node_test.go#L281

Anyway, I'll see if I can repro what you're seeing.

**Comment by otoolep** [comment] 2021-01-04 13:04
I ran a simple 5.4.1 -> 5.8.0 test, and don't see any issues. 
```
~ $ mkdir upgrade
~ $ cd upgrade/
~/upgrade $ curl -L https://github.com/rqlite/rqlite/releases/download/v5.4.1/rqlite-v5.4.1-linux-amd64.tar.gz -o rqlite-v5.4.1-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   656  100   656    0     0   2902      0 --:--:-- --:--:-- --:--:--  2889
100 16.7M  100 16.7M    0     0  7719k      0  0:00:02  0:00:02 --:--:-- 11.8M
~/upgrade $ tar xvfz rqlite-v5.4.1-linux-amd64.tar.gz
rqlite-v5.4.1-linux-amd64/
rqlite-v5.4.1-linux-amd64/rqlite
rqlite-v5.4.1-linux-amd64/rqbench
rqlite-v5.4.1-linux-amd64/rqlited
~/upgrade $ curl -L https://github.com/rqlite/rqlite/releases/download/v5.8.0/rqlite-v5.8.0-linux-amd64.tar.gz -o rqlite-v5.8.0-linux-amd64.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   656  100   656    0     0   3247      0 --:--:-- --:--:-- --:--:--  3247
100 19.0M  100 19.0M    0     0  8445k      0  0:00:02  0:00:02 --:--:-- 11.2M
~/upgrade $ tar xvfz rqlite-v5.8.0-linux-amd64.tar.gz
rqlite-v5.8.0-linux-amd64/
rqlite-v5.8.0-linux-amd64/rqlite
rqlite-v5.8.0-linux-amd64/rqbench
rqlite-v5.8.0-linux-amd64/rqlited
~/upgrade $ rqlite-v5.4.1-linux-amd64/rqlited ~/node.1

            _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |
         |_|
                                                                                                                                                                                                           
[rqlited] 2021/01/04 08:00:11 rqlited starting, version v5.4.1, commit d446233b3e60b5dd9c8fbfcf4c3a36b2731d6a94, branch master                                                                             
[rqlited] 2021/01/04 08:00:11 go1.14, target architecture is amd64, operating system target is linux                                                                                                       
[store] 2021/01/04 08:00:11 opening store with node ID localhost:4002                                                                                                                                      
[store] 2021/01/04 08:00:11 ensuring directory at /home/philip/node.1 exists                                                                                                                               
[store] 2021/01/04 08:00:11 SQLite in-memory database opened                                                                                                                                               
2021-01-04T08:00:11.806-0500 [INFO]  raft: Initial configuration (index=0): []                                                                                                                             
[store] 2021/01/04 08:00:11 bootstrap needed                                                                                                                                                               
2021-01-04T08:00:11.806-0500 [INFO]  raft: Node at 127.0.0.1:4002 [Follower] entering Follower state (Leader: "")                                                                                          
[rqlited] 2021/01/04 08:00:11 no join addresses set                                                                                                                                                        
2021-01-04T08:00:13.728-0500 [WARN]  raft: Heartbeat timeout from "" reached, starting election                                                                                                            
2021-01-04T08:00:13.728-0500 [INFO]  raft: Node at 127.0.0.1:4002 [Candidate] entering Candidate state in term 2                                                                                           
2021-01-04T08:00:13.765-0500 [INFO]  raft: Election won. Tally: 1                                                                                                                                          
2021-01-04T08:00:13.765-0500 [INFO]  raft: Node at 127.0.0.1:4002 [Leader] entering Leader state                                                                                                           
[store] 2021/01/04 08:00:13 waiting for up to 2m0s for application of initial logs                                                                                                                         
[http] 2021/01/04 08:00:13 service listening on localhost:4001                                                                                                                                             
^Cerror accepting:  accept tcp 127.0.0.1:4002: use of closed network connection                                                                                                                            
[rqlited] 2021/01/04 08:00:48 rqlite server stopped
~/upgrade $ rqlite-v5.8.0-linux-amd64/rqlited ~/node.1

            _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |               www.rqlite.com
         |_|

[rqlited] 2021/01/04 08:00:59 rqlited starting, version v5.8.0, commit b41e5c19c5875f559bb523397f2e00d567df21a4, branch master
[rqlited] 2021/01/04 08:00:59 go1.14, target architecture is amd64, operating system target is linux
[rqlited] 2021/01/04 08:00:59 preexisting node state detected in /home/philip/node.1
[rqlited] 2021/01/04 08:00:59 no join addresses set
[store] 2021/01/04 08:00:59 opening store with node ID localhost:4002
[store] 2021/01/04 08:00:59 ensuring directory at /home/philip/node.1 exists
[store] 2021/01/04 08:00:59 SQLite in-memory database opened
2021-01-04T08:00:59.062-0500 [INFO]  raft: initial configuration: index=1 servers="[{Suffrage:Voter ID:localhost:4002 Address:127.0.0.1:4002}]"
[store] 2021/01/04 08:00:59 no cluster bootstrap requested
2021-01-04T08:00:59.062-0500 [INFO]  raft: entering follower state: follower="Node at 127.0.0.1:4002 [Follower]" leader=
2021-01-04T08:01:00.832-0500 [WARN]  raft: heartbeat timeout reached, starting election: last-leader=
2021-01-04T08:01:00.832-0500 [INFO]  raft: entering candidate state: node="Node at 127.0.0.1:4002 [Candidate]" term=3
2021-01-04T08:01:00.860-0500 [INFO]  raft: election won: tally=1
2021-01-04T08:01:00.860-0500 [INFO]  raft: entering leader state: leader="Node at 127.0.0.1:4002 [Leader]"
[store] 2021/01/04 08:01:00 waiting for up to 2m0s for application of initial logs
[http] 2021/01/04 08:01:00 service listening on 127.0.0.1:4001
[rqlited] 2021/01/04 08:01:00 node is ready
```

I inserted records using the 5.4.1 node, and was able to read them back after restarting the node with 5.8.0
```
~/upgrade $ rqlite-v5.4.1-linux-amd64/rqlite
Welcome to the rqlite CLI. Enter ".help" for usage hints.
127.0.0.1:4001> CREATE TABLE foo (id INTEGER NOT NULL PRIMARY KEY, name TEXT)
0 row affected
127.0.0.1:4001> INSERT INTO foo(name) VALUES("fiona")
1 row affected
127.0.0.1:4001> SELECT * FROM foo
+----+-------+
| id | name  |
+----+-------+
| 1  | fiona |
+----+-------+
127.0.0.1:4001> SELECT * FROM foo
+----+-------+
| id | name  |
+----+-------+
| 1  | fiona |
+----+-------+
127.0.0.1:4001> 
EOF (CTRL+D)
~/upgrade $ rqlite-v5.8.0-linux-amd64/rqlite
Welcome to the rqlite CLI. Enter ".help" for usage hints.
127.0.0.1:4001> SELECT * FROM foo
+----+-------+
| id | name  |
+----+-------+
| 1  | fiona |
+----+-------+
127.0.0.1:4001> 
``

**Comment by otoolep** [comment] 2021-01-04 13:05
Can you show me a session such as this? Are you running a single node, or a cluster? What OS are you running on?

**Comment by otoolep** [comment] 2021-01-05 19:39
I just created a 3-node cluster using 5.4.0, inserted a record and then upgraded every node to 5.8.0. No problems encountered.

Right now I cannot reproduce any upgrade issues.

**Comment by otoolep** [comment] 2021-01-14 13:50
No further updates, closing.

**Closed by otoolep** 2021-01-14 13:50 UTC
