### ISSUE TITLE
Support for blob parameters

### ISSUE THREAD

**Issue by refi64** [rqlite/rqlite#1346] opened 2023-07-14 00:25 UTC
There doesn't seem to be any way to insert blobs into a table:

```
$ xh localhost:4001/db/request '[0]'='CREATE TABLE blobs (b blob) STRICT'
[...]
# is it a plain string?
$ xh localhost:4001/db/request '[0][0]'='INSERT INTO blobs VALUES (?)' '[0][1]':='"abc"'
HTTP/1.1 200 OK
Content-Length: 72
Content-Type: application/json; charset=utf-8
Date: Fri, 14 Jul 2023 00:15:50 GMT
X-Rqlite-Version: v7.21.4

{
    "results": [
        {
            "error": "cannot store TEXT value in BLOB column blobs.b"
        }
    ]
}
# ...maybe an array of bytes?
$ xh localhost:4001/db/request '[0][0]'='INSERT INTO blobs VALUES (?)' '[0][1]':='[10, 11]'
HTTP/1.1 400 Bad Request
Content-Length: 17
Content-Type: text/plain; charset=utf-8
Date: Fri, 14 Jul 2023 00:16:04 GMT
X-Content-Type-Options: nosniff
X-Rqlite-Version: v7.21.4

unsupported type
# uhhh how about base64
$ xh localhost:4001/db/request '[0][0]'='INSERT INTO blobs VALUES (?)' '[0][1]':='"q80="'
HTTP/1.1 200 OK
Content-Length: 72
Content-Type: application/json; charset=utf-8
Date: Fri, 14 Jul 2023 00:16:36 GMT
X-Rqlite-Version: v7.21.4

{
    "results": [
        {
            "error": "cannot store TEXT value in BLOB column blobs.b"
        }
    ]
}
```

If I look at the source code where this is parsed, it seems like the only way to get this is [via a `[]byte`](https://github.com/rqlite/rqlite/blob/4e7f2023063da2c5ab7d6a6878086f89676fe188/http/request_parser.go#L120):

```go
func makeParameter(name string, i interface{}) (*command.Parameter, error) {
	// [...]
	case []byte:
		return &command.Parameter{
			Value: &command.Parameter_Y{
				Y: v,
			},
			Name: name,
		}, nil
```

Except...this is deserialized from JSON, there's no way for me to specify `[]byte` :sweat_smile: All I in terms of the basic atoms are strings and numbers.

**Comment by otoolep** [comment] 2023-07-14 00:43
Thanks for the report. I'm open to suggestions on how the API could change to support this. Perhaps some special query param in the URL? Or interpret any base64 encoded value as blob? It would be a string object in the API, but rqlite would check if something was base64 encoded and convert to a `[]byte`. WDYT?

**Comment by refi64** [comment] 2023-07-19 01:02
Hmm that would run the risk of actual strings that look like base64 being converted, no?

As a thought: maps are not used for values anywhere yet. Perhaps something like `{"blob": "[base64 here]"}` would work? It would still clearly distinguish this, as well as maybe leave room for any sqlite extensions with their own types in the future. (Same format could be used for #1345?)

**Comment by otoolep** [comment] 2023-07-19 11:57
>Hmm that would run the risk of actual strings that look like base64 being converted, no?

Yes, but what are the chances you create a string that happens to just look like it's base64 encocded, vs. the much more likely possibility that people will prefer a simpler API. :-) Go has a package in the standard library that can help.,

https://pkg.go.dev/encoding/base64

**Comment by otoolep** [comment] 2023-07-19 11:59
We could always add to the API to allow users *disable* the autodetection. In other words, the API supports the most common scenario by default, but would allow an escape hatch.

**Comment by refi64** [comment] 2023-07-20 01:30
There are a lot of cases where strings you insert are relatively arbitrary: in my own scenario, I'm storing things like environment variables (where e.g. base64-encoded keys would be a totally normal thing to store), as well as binary data, and potentially *both in the same transaction* (and potentially in the same row). So, anything that revolves around automatically assuming based on base64-encoding w/ a global toggle wouldn't work that well... With that, the only way to use blobs in the right places would be to make all the user-controlled string columns `any` (or not use strict mode I guess?), which adds a lot of overhead and would be a *massive* footgun if you forget about that.

It's also worth noting that the empty string in base64 is...well, empty (see `echo -n | base64`), so there would still be no way of distinguishing between an empty string and empty blob; you'd have to convert all empty blobs to NULL or similar first, which isn't that great...

I did notice there were no other issues filed related to this, which also makes me think that blobs aren't commonly used with rqlite. In that case, having a very marginally more complicated value representation feels fine? And reduces the risk of breaking existing code due to the aforementioned reasons.

(*Technically* as-is I could really just leave all the binary data as a base64 string! It's just a fair bit more storage usage, ~33% size inflation, but I'd honestly prefer it to magic blob-or-not detection.)

**Comment by otoolep** [comment] 2023-07-20 22:16
Hang on, the first error you reported is exactly the same when you talk to SQLite directly:
```bash
sqlite> CREATE TABLE blobs (b blob) STRICT;
sqlite> INSERT INTO blobs VALUES("abc");
Runtime error: cannot store TEXT value in BLOB column blobs.b (19)
sqlite> 
```
So what you got back from rqlite is the same thing as you get back from SQLite. Just so we're clear, can you show me SQLite doing what you want to do, but you being unable to do the exact same thing with rqlite?

**Comment by otoolep** [comment] 2023-07-20 22:36
Reading the SQLite docs, this is one way to insert blob data:
```bash
sqlite> CREATE TABLE Files(Name TEXT, Data BLOB);
sqlite> INSERT INTO Files(Name, Data) VALUES('Example', X'74657374');
sqlite> SELECT Name, hex(Data) FROM Files WHERE Name = 'Example';
Example|74657374
```

From https://www.sqlite.org/lang_expr.html

> BLOB literals are string literals containing hexadecimal data and preceded by a single "x" or "X" character. Example: X'53514C697465' 

I think this kind of thing can be inserted today, but reading it back my need some work. See https://github.com/rqlite/rqlite/pull/1351

**Comment by otoolep** [comment] 2023-07-20 22:37
The linked PR is a unit test at the DB level, I'm attempting to show that you can insert BLOBs programatically today.

**Comment by otoolep** [comment] 2023-07-20 22:38
I am trying to focus on getting 8.0 out the door however, any bug fixes or changes related to this will be part of that release. So you might have to wait a little while (weeks).

**Comment by OwlHatSoftware** [comment] 2024-01-11 14:17
> Reading the SQLite docs, this is one way to insert blob data:
> 
> ```shell
> sqlite> CREATE TABLE Files(Name TEXT, Data BLOB);
> sqlite> INSERT INTO Files(Name, Data) VALUES('Example', X'74657374');
> sqlite> SELECT Name, hex(Data) FROM Files WHERE Name = 'Example';
> Example|74657374
> ```
> 
> From https://www.sqlite.org/lang_expr.html
> 
> > BLOB literals are string literals containing hexadecimal data and preceded by a single "x" or "X" character. Example: X'53514C697465'
> 
> I think this kind of thing can be inserted today into rqlite, but reading it back my need some work. See #1351

This is exactly how it works. Just finished a unit test involving this. I am writing a Delphi client for rqlite. In the test I convert a piece of 'Lorem ipsum' text to a hex byte representation. You can write it in your insert statement preceded by an "X", just as Philip replied.

**Comment by otoolep** [comment] 2024-01-11 14:48
Thanks. I do think the API needs work on the response side of things, however. It's converting returned BLOB data to base-base encoded data, and it's not super clear. I plan to look into this soon, to make it responses more specific and less ambigious. Docs needs work too.

**Comment by otoolep** [comment] 2024-01-11 16:22
@OwlHatSoftware -- if your client will be open source, I'd like to list it here (when ready): https://rqlite.io/docs/api/client-libraries/

**Comment by OwlHatSoftware** [comment] 2024-01-11 16:51
> @OwlHatSoftware -- if your client will be open source, I'd like to list it here (when ready): https://rqlite.io/docs/api/client-libraries/

Of course, I will send you the link to my github repo when it is ready.

**Comment by otoolep** [comment] 2024-02-19 15:34
I believe this has been answered since you can store them values. The issue is unambigously reading them back. There are other issues tracking that.

**Comment by otoolep** [comment] 2024-02-19 15:34
https://github.com/rqlite/rqlite/issues/1345

https://github.com/rqlite/rqlite/issues/1691

**Closed by otoolep** 2024-02-19 15:34 UTC
