### ISSUE TITLE
Common Table Expression support

### ISSUE THREAD

**Issue by alanjds** [rqlite/rqlite#255] opened 2017-01-13 21:11 UTC
I am updating [pyrqlite](https://github.com/rqlite/pyrqlite) to complain with the official sqlite driver of Python as much as possible. 

Most of the work done is on my fork on branch [test-types]( https://github.com/alanjds/pyrqlite/tree/tests-types) for now.

However, one test ported from the official module suggests that RQLite does not support a feature so called "Common Table Expression". The code that tests this support is here: https://github.com/alanjds/pyrqlite/blob/tests-types/src/test/test_types.py#L333

I am running the tests with DEBUG loglevel and, before the test fail, the SELECT is issued with success and but I saw no row nor columns info returned. It suggests me that, as the underlying SQLite version does support the feature, RQLite had not implemented it.

Could someone please clarify, as I am not "that" used to SQLite nor RQLite internals?

Thanks.

**Comment by otoolep** [comment] 2017-01-13 22:20
Looking into this now, I too am seeing some unexpected behaviour.

**Comment by otoolep** [comment] 2017-01-13 22:25
```
$ curl -v -XGET 'localhost:4001/db/query?pretty&timings' -H 'Content-Type: application/json' -d '[
    "with bar as (select * from test) select * from test where x = 1"
]'
*   Trying ::1...
* connect to ::1 port 4001 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4001 (#0)
> GET /db/query?pretty&timings HTTP/1.1
> Host: localhost:4001
> User-Agent: curl/7.43.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 73
> 
* upload completely sent off: 73 out of 73 bytes
< HTTP/1.1 400 Bad Request
< Content-Type: application/json; charset=utf-8
< X-Rqlite-Version: 3
< Date: Fri, 13 Jan 2017 22:19:25 GMT
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```
Don't know why this is a bad request.

**Comment by otoolep** [comment] 2017-01-13 22:37
It's not an issue with the database or SQL layer, since this passes:

https://github.com/rqlite/rqlite/pull/256

Continuing to investigate.

**Comment by otoolep** [comment] 2017-01-13 22:41
Actually, I take it back, my `curl` request is wrong. rqlite supports this kind of thing fine:

```
$ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=with bar as (select * from test) select * from test where x = 1'
{
    "results": [
        {
            "columns": [
                "x"
            ],
            "types": [
                "foo"
            ],
            "values": [
                [
                    1
                ]
            ],
            "time": 0.002032388
        }
    ],
    "time": 0.0020779540000000003
}~/repos/rqlite/src/github.com/rqlite/rqlite/store (with_views)$ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=with bar as (select * from test) select * from test where x = 2'
{
    "results": [
        {
            "columns": [
                "x"
            ],
            "types": [
                "foo"
            ],
            "time": 0.00010383
        }
    ],
    "time": 0.00012452
}
```
Perhaps you're building the request to rqlite incorrectly? As you can see, I can drive the HTTP API to get the right results -- you just need your Python library to do the same thing.

**Comment by otoolep** [comment] 2017-01-13 22:44
I am tempted to close this, as I now don't see anything wrong with rqlite. The CLI does *not* support it correctly, but that is a CLI issue, not a rqlite issue:

https://github.com/rqlite/rqlite/issues/257

**Comment by otoolep** [comment] 2017-01-13 22:45
Here is more detail of the successful request:
```
$ curl -vv -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=with bar as (select * from test) select * from test where x = 1'
*   Trying ::1...
* connect to ::1 port 4001 failed: Connection refused
*   Trying 127.0.0.1...
* Connected to localhost (127.0.0.1) port 4001 (#0)
> GET /db/query?pretty&timings&q=with%20bar%20as%20%28select%20%2A%20from%20test%29%20select%20%2A%20from%20test%20where%20x%20%3D%201 HTTP/1.1
> Host: localhost:4001
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: application/json; charset=utf-8
< X-Rqlite-Version: 3
< Date: Fri, 13 Jan 2017 22:45:19 GMT
< Content-Length: 342
< 
{
    "results": [
        {
            "columns": [
                "x"
            ],
            "types": [
                "foo"
            ],
            "values": [
                [
                    1
                ]
            ],
            "time": 0.00012175100000000001
        }
    ],
    "time": 0.00015008300000000002
* Connection #0 to host localhost left intact
}
```

**Comment by otoolep** [comment] 2017-01-13 22:46
@alanjds -- I'm closing this issue since it does not appear to be an issue with rqlite. Please re-open if you believe I am incorrect. I am happy to answer more questions on this ticket however.

**Comment by alanjds** [comment] 2017-01-14 12:35
I see. Yours looks to be working. What version of RQLite are you using? I see a naked "X-Rqlite-Version: 3" header on your responses.

Mine shows  "X-Rqlite-Version: v3.9.1"

**Comment by otoolep** [comment] 2017-01-14 16:34
I simply built top of tree. There is only a small difference between top-of-tree and 3.9.1.

**Comment by otoolep** [comment] 2017-01-14 16:41
Oh, I forgot one key thing.

During my testing I passed `-nosel` to rqlited on startup. This tells the system not to check that queries only start with `SELECT`. At the time I didn't realise queries could start with `WITH`.

So start `rqlited` like so: `rqlited -nosel your_data_dir`

**Comment by otoolep** [comment] 2017-01-14 16:41
I'm going to remove this restriction now, since it was never valid.

**Comment by otoolep** [comment] 2017-01-14 17:05
Fixed in 3.9.2.

By the way, you should have been getting HTTP 403 back from the HTTP API, if I believe what was going on was going on.

**Closed by otoolep** 2017-01-14 17:05 UTC

**Comment by alanjds** [comment] 2017-01-16 15:49
Tried with the just-relased 3.9.2: Seems to be unrelated to ``-nosel``. This is the captured network stream with Wireshark:

```
POST /db/execute?transaction HTTP/1.1
Host: localhost:4001
Accept-Encoding: identity
Content-Length: 28
Content-Type: application/json

["create table test(x foo)"]

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Rqlite-Version: v3.9.2
Date: Mon, 16 Jan 2017 15:45:54 GMT
Content-Length: 52

{"results":[{"last_insert_id":1,"rows_affected":1}]}

POST /db/execute?transaction HTTP/1.1
Host: localhost:4001
Accept-Encoding: identity
Content-Length: 31
Content-Type: application/json

["insert into test values (1)"]

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Rqlite-Version: v3.9.2
Date: Mon, 16 Jan 2017 15:45:54 GMT
Content-Length: 52

{"results":[{"last_insert_id":1,"rows_affected":1}]}

POST /db/execute?transaction HTTP/1.1
Host: localhost:4001
Accept-Encoding: identity
Content-Length: 67
Content-Type: application/json

["with bar as (select * from test) select * from test where x = 1"]

HTTP/1.1 200 OK
Content-Type: application/json; charset=utf-8
X-Rqlite-Version: v3.9.2
Date: Mon, 16 Jan 2017 15:45:54 GMT
Content-Length: 52

{"results":[{"last_insert_id":1,"rows_affected":1}]}
```

I am trying to build from the sources right now to see if it changes anything besides the version header.

**Comment by otoolep** [comment] 2017-01-16 16:48
You're doing it wrong. 

Must send queries to the /query endpoint, and use GET. Please re-read the Data API documentation,  or check my example above.

**Comment by alanjds** [comment] 2017-01-16 17:11
Hum... So the issue cames from here? https://github.com/rqlite/pyrqlite/blob/master/src/pyrqlite/cursors.py#L98

Anyway, I would expect that everything that works on ``/db/query`` to work on ``/db/execute`` too. Thanks for pointing the difference.

Now I am thinking in how to detect on client side if some query alters data...

**Comment by otoolep** [comment] 2017-01-16 17:31
It may actually be working. The behaviour is undefined.

**Comment by otoolep** [comment] 2017-01-16 17:32
I do agree that the next major enhancement to rqlite would be to have it do the right thing automatically. This would make it much easier to use. 

It's a high-priority next task.
