### ISSUE TITLE
rqlite nodes crashine with no apparent reason

### ISSUE THREAD

**Issue by Theog75** [rqlite/rqlite#830] opened 2021-07-21 18:06 UTC
**What version are you running?**
verision 6.0.1

**What did you do?**
ran a cluster of 5 rqlite nodes on k8s

**What did you expect to happen?**
rqlite nodes should be stable

**What happened instead?**
nodes crash with the following log:
```
2021-07-21T18:04:09.076Z [WARN]  raft: heartbeat timeout reached, starting election: last-leader=10.244.250.158:4002
2021-07-21T18:04:09.076Z [INFO]  raft: entering candidate state: node="Node at 10.244.242.39:4002 [Candidate]" term=3
2021-07-21T18:04:09.082Z [INFO]  raft: election won: tally=2
2021-07-21T18:04:09.082Z [INFO]  raft: entering leader state: leader="Node at 10.244.242.39:4002 [Leader]"
2021-07-21T18:04:09.082Z [INFO]  raft: added peer, starting replication: peer=rqlite-0
2021-07-21T18:04:09.082Z [INFO]  raft: added peer, starting replication: peer=rqlite-4
2021-07-21T18:04:09.083Z [WARN]  raft: appendEntries rejected, sending older logs: peer="{Voter rqlite-0 10.244.250.158:4002}" next=1
2021-07-21T18:04:09.084Z [INFO]  raft: pipelining replication: peer="{Voter rqlite-4 10.244.42.143:4002}"
2021-07-21T18:04:09.352Z [INFO]  raft: pipelining replication: peer="{Voter rqlite-0 10.244.250.158:4002}"
[rqlited] 2021/07/21 18:04:10 http: panic serving 10.244.193.211:50948: interface conversion: interface {} is nil, not *store.fsmExecuteResponse
goroutine 2256 [running]:
net/http.(*conn).serve.func1(0xc000250460)
	/usr/local/go/src/net/http/server.go:1824 +0x153
panic(0xbb7fa0, 0xc00037e000)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/rqlite/rqlite/store.(*Store).execute(0xc000240000, 0xc000ab80c0, 0x416c38, 0x48, 0xc1d520, 0xc00022a101, 0xc000226050)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/store/store.go:593 +0x4a9
github.com/rqlite/rqlite/store.(*Store).Execute(0xc000240000, 0xc000ab80c0, 0x26000, 0xc000010008, 0x1, 0x1, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/store/store.go:538 +0x78
github.com/rqlite/rqlite/http.(*Service).handleExecute(0xc00016c0f0, 0xd6e0b0, 0xc000ab0000, 0xc000456100)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/http/service.go:740 +0x41c
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc00016c0f0, 0xd6e0b0, 0xc000ab0000, 0xc000456100)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/http/service.go:262 +0x651
net/http.serverHandler.ServeHTTP(0xc000ab01c0, 0xd6e0b0, 0xc000ab0000, 0xc000456100)
	/usr/local/go/src/net/http/server.go:2887 +0xa3
net/http.(*conn).serve(0xc000250460, 0xd6f660, 0xc000411100)
	/usr/local/go/src/net/http/server.go:1952 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3013 +0x39b
panic: interface conversion: driver.Stmt is nil, not *sqlite3.SQLiteStmt

goroutine 37 [running]:
github.com/rqlite/go-sqlite3.(*SQLiteConn).exec(0xc000218240, 0xd6f5f0, 0xc0000c8060, 0xc000a6c000, 0x1e1c6, 0x11628f8, 0x0, 0x0, 0xc00043b960, 0x47781b, ...)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:803 +0x78e
github.com/rqlite/go-sqlite3.(*SQLiteConn).Exec(0xc000218240, 0xc000a6c000, 0x1e1c6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:792 +0x138
github.com/rqlite/rqlite/db.(*DB).Execute.func1(0xc00043baf0, 0xc9a400, 0xc0002005a0, 0xc0005b6c30, 0x1501, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:321 +0x2b4
github.com/rqlite/rqlite/db.(*DB).Execute(0xc0002005a0, 0xc0005b6c30, 0xc000420101, 0x0, 0x0, 0x0, 0x0, 0xc00043bc18)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:356 +0xa5
github.com/rqlite/rqlite/store.(*Store).Apply(0xc000240000, 0xc000490398, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/store/store.go:940 +0x3c7
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc00058a5c0)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:90 +0x2c6
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc000376400, 0x1, 0x40)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:113 +0x78
github.com/hashicorp/raft.(*Raft).runFSM(0xc000272000)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:216 +0x392
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc000272000, 0xc000204280)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:144 +0x66

```

**Comment by Theog75** [comment] 2021-07-21 18:06
dor@sosiv.io please followup

**Comment by otoolep** [comment] 2021-07-21 19:31
Thanks for the report. Do you have the *entire* log? From the very start it booted up? Or had the node been running for a while, so the initial part of the log was gone?

**Comment by otoolep** [comment] 2021-07-21 20:04
Also, I don't think you're actually running 6.0.1, since the lines in log output do not match lines in the source at 6.0.1. Are you certain you're running 6.0.1?

`github.com/rqlite/rqlite/store.(*Store).Execute` is actually at line 540, not 538 (as per your log):

https://github.com/rqlite/rqlite/blob/v6.0.1/store/store.go#L540

**Comment by otoolep** [comment] 2021-07-21 20:27
I would guess this is the same as https://github.com/rqlite/rqlite/issues/812

**Comment by otoolep** [comment] 2021-07-21 20:58
This looks pretty deep in the database layer, and it's not immediately clear to me what is going on. I think it's being triggered by this line:

https://github.com/rqlite/go-sqlite3/blob/master/sqlite3.go#L803

where the type assertion fails. But it's not clear to me at all how this could happen.

**Comment by Theog75** [comment] 2021-07-21 21:00
full log (the begining is our addition to the bash script):
```
Rqlite K8s V1.1
Found leader rqlite-1

rqlite-1
rqlite-1 --- rqlite-1 = 1
rqlite-1
rqlite-2 --- rqlite-1 = 2
rqlite-1
rqlite-3 --- rqlite-1 = 3
rqlite-1
rqlite-4 --- rqlite-1 = 4
rqlite-1 is the chosen one all hail rqlite-1
cannot resolve hostname rqlite-0.rqlite
Trying to join cluster at rqlite-1.....

            _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |               www.rqlite.com
         |_|

[rqlited] 2021/07/21 19:53:27 rqlited starting, version 6, commit unknown, branch unknown
[rqlited] 2021/07/21 19:53:27 go1.16.2, target architecture is amd64, operating system target is linux
[rqlited] 2021/07/21 19:53:27 launch command: /rqlited -node-id rqlite-0 -raft-snap 4096 -raft-timeout 4s -raft-election-timeout 5s -join-attempts 5 -http-addr rqlite-0.rqlite:4001 -raft-addr rqlite-0.rqlite:4002 -join http://rqlite-1.rqlite:4001 /node
[rqlited] 2021/07/21 19:53:27 no preexisting node state detected in /node, node may be bootstrapping
[rqlited] 2021/07/21 19:53:27 join addresses specified, node is not bootstrapping
[store] 2021/07/21 19:53:27 opening store with node ID rqlite-0
[store] 2021/07/21 19:53:27 ensuring directory at /node exists
[mux] 2021/07/21 19:53:27 mux serving on 10.244.250.158:4002, advertising 10.244.250.158:4002
[store] 2021/07/21 19:53:27 0 preexisting snapshots present
[store] 2021/07/21 19:53:27 first log index: 0, last log index: 0, last command log index: 0:
2021-07-21T19:53:27.290Z [INFO]  raft: initial configuration: index=0 servers=[]
[store] 2021/07/21 19:53:27 no cluster bootstrap requested
[rqlited] 2021/07/21 19:53:27 join addresses are: [http://rqlite-1.rqlite:4001]
2021-07-21T19:53:27.290Z [INFO]  raft: entering follower state: follower="Node at 10.244.250.158:4002 [Follower]" leader=
[mux] 2021/07/21 19:53:27 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[rqlited] 2021/07/21 19:53:27 successfully joined cluster at http://rqlite-1.rqlite:4001/join
[mux] 2021/07/21 19:53:27 tcp.Mux: handler not registered: 2 (unsupported protocol?)
[store] 2021/07/21 19:53:27 waiting for up to 2m0s for application of initial logs
[cluster] 2021/07/21 19:53:27 service listening on 10.244.250.158:4002
[http] 2021/07/21 19:53:27 service listening on 10.244.250.158:4001
[rqlited] 2021/07/21 19:53:27 node is ready
2021-07-21T19:53:29.851Z [WARN]  raft: failed to get previous log: previous-index=29169 last-index=0 error="log not found"
2021-07-21T19:53:29.931Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/2-26367-1626897209931.tmp
2021-07-21T19:53:30.626Z [INFO]  raft: copied to local snapshot: bytes=37386008
[store] 2021/07/21 19:53:32 node restored in 2.279724399s
2021-07-21T19:53:32.953Z [INFO]  raft: Installed remote snapshot
[store] 2021/07/21 19:59:57 node snapshot created in 278.338143ms
2021-07-21T19:59:57.671Z [INFO]  raft: starting snapshot up to: index=30473
2021-07-21T19:59:57.671Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/2-30473-1626897597671.tmp
[store] 2021/07/21 20:00:09 snapshot and persist took 12.511347475s
2021-07-21T20:00:09.904Z [INFO]  raft: no logs to truncate
2021-07-21T20:00:09.904Z [INFO]  raft: snapshot complete up to: index=30473
panic: interface conversion: driver.Stmt is nil, not *sqlite3.SQLiteStmt

goroutine 13 [running]:
github.com/rqlite/go-sqlite3.(*SQLiteConn).exec(0xc000096660, 0xd6f5f0, 0xc0000300a8, 0xc0007a6000, 0x1be4c, 0x11628f8, 0x0, 0x0, 0xc001191960, 0x47781b, ...)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:803 +0x78e
github.com/rqlite/go-sqlite3.(*SQLiteConn).Exec(0xc000096660, 0xc0007a6000, 0x1be4c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0)
	/home/theog/go/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:792 +0x138
github.com/rqlite/rqlite/db.(*DB).Execute.func1(0xc001191af0, 0xc9a400, 0xc0002d0f90, 0xc001522910, 0x1501, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:321 +0x2b4
github.com/rqlite/rqlite/db.(*DB).Execute(0xc0002d0f90, 0xc001522910, 0xc0000a8a01, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/db/db.go:356 +0xa5
github.com/rqlite/rqlite/store.(*Store).Apply(0xc0001fa180, 0xc0014d7320, 0x0, 0x0)
	/home/theog/go/src/rqlitesource/src/github.com/rqlite/rqlite/store/store.go:940 +0x3c7
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc000383380)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:90 +0x2c6
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc00027a400, 0x1, 0x40)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:113 +0x78
github.com/hashicorp/raft.(*Raft).runFSM(0xc0001a6f00)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:216 +0x392
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0001a6f00, 0xc0001c0dd0)
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/theog/go/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:144 +0x66

```

**Comment by otoolep** [comment] 2021-07-21 21:02
Thanks.

I just want to point out that you're not running 6.0.1. You seem to be running  your own build. I don't think it matters for this issue, but if you could run the official 6.0.1 release, that would remove that factor.

https://github.com/rqlite/rqlite/releases/tag/v6.0.1

or

docker pull rqlite/rqlite latest

**Comment by otoolep** [comment] 2021-07-21 21:04
I don't suppose you can repro this on demand? It's random and rare?

**Comment by Theog75** [comment] 2021-07-21 21:19
just downloaded packed and deployed I'll post an update tomorrow :crossed_fingers:

**Comment by Dorsosiv** [comment] 2021-07-21 21:19
Hi @otoolep ,  its weird that you say that it is not 6.0.1 because I cloned the repo and did go build for the cmds

**Comment by Theog75** [comment] 2021-07-22 10:05
@Dorsosiv I think @otoolep gave us an alpha version and we tested it and stayed with it - yesterday I redeployed after downloading the new version - and up until now - it seems stable - lets wait and see

**Comment by otoolep** [comment] 2021-07-22 12:28
OK, thanks guys. I'm not sure how much of a difference it'll make, not much I suspect. What is happening is pretty low-down in the rqlite system, and it's not immediately clear to me how it's happening. 

If it happens again, the whole log from the crashed node would be good. Also, the entire data directory zipped up from the leader node could help. But I'm not sure if you can share that with me, as you may have proprietary information in there.

I assume that when this happens, just trying to start the crashed node works OK?

**Comment by Theog75** [comment] 2021-07-22 15:24
happened again :( there are 40 queries in about 5 seconds:
```
          _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |               www.rqlite.com
         |_|

[rqlited] 2021/07/22 13:49:49 rqlited starting, version v6.0.1, commit b9b11db1aa49e4a2b9661c633ff4e4d3f961f526, branch master
[rqlited] 2021/07/22 13:49:49 go1.15.7, target architecture is amd64, operating system target is linux
[rqlited] 2021/07/22 13:49:49 launch command: /rqlited -node-id rqlite-0 -raft-snap 12288 -raft-timeout 6s -raft-election-timeout 8s -join-attempts 5 -http-addr rqlite-0.rqlite:4001 -raft-addr rqlite-0.rqlite:4002 -raft-log-level INFO -join http://rqlite-3.rqlite:4001 /node
[mux] 2021/07/22 13:49:49 received handler registration request for header 1
[mux] 2021/07/22 13:49:49 received handler registration request for header 2
[cluster] 2021/07/22 13:49:49 service listening on 10.244.42.134:4002
[mux] 2021/07/22 13:49:49 mux serving on 10.244.42.134:4002, advertising 10.244.42.134:4002
[rqlited] 2021/07/22 13:49:49 no preexisting node state detected in /node, node may be bootstrapping
[rqlited] 2021/07/22 13:49:49 join addresses specified, node is not bootstrapping
[store] 2021/07/22 13:49:49 opening store with node ID rqlite-0
[store] 2021/07/22 13:49:49 ensuring directory at /node exists
[store] 2021/07/22 13:49:49 0 preexisting snapshots present
[store] 2021/07/22 13:49:49 first log index: 0, last log index: 0, last command log index: 0:
2021-07-22T13:49:49.774Z [INFO]  raft: initial configuration: index=0 servers=[]
[store] 2021/07/22 13:49:49 no cluster bootstrap requested
[rqlited] 2021/07/22 13:49:49 join addresses are: [http://rqlite-3.rqlite:4001]
2021-07-22T13:49:49.774Z [INFO]  raft: entering follower state: follower="Node at 10.244.42.134:4002 [Follower]" leader=
2021-07-22T13:49:49.784Z [WARN]  raft: failed to get previous log: previous-index=1939 last-index=0 error="log not found"
[rqlited] 2021/07/22 13:49:49 successfully joined cluster at http://rqlite-3.rqlite:4001/join
[store] 2021/07/22 13:49:49 waiting for up to 2m0s for application of initial logs
[rqlited] 2021/07/22 13:49:50 store has reached consensus
[http] 2021/07/22 13:49:50 service listening on 10.244.42.134:4001
[rqlited] 2021/07/22 13:49:50 node is ready
[store] 2021/07/22 14:10:10 node snapshot created in 217.710239ms
2021-07-22T14:10:10.603Z [INFO]  raft: starting snapshot up to: index=12645
2021-07-22T14:10:10.603Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/2-12645-1626963010603.tmp
[store] 2021/07/22 14:10:18 snapshot and persist took 7.846167303s
2021-07-22T14:10:18.231Z [INFO]  raft: snapshot complete up to: index=12645
[store] 2021/07/22 14:29:35 node snapshot created in 313.514337ms
2021-07-22T14:29:35.408Z [INFO]  raft: starting snapshot up to: index=25150
2021-07-22T14:29:35.408Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/2-25150-1626964175408.tmp
[store] 2021/07/22 14:29:48 snapshot and persist took 13.360436522s
2021-07-22T14:29:48.454Z [INFO]  raft: compacting logs: from=1 to=9938
2021-07-22T14:29:48.548Z [INFO]  raft: snapshot complete up to: index=25150
[store] 2021/07/22 14:46:48 node snapshot created in 642.234861ms
2021-07-22T14:46:48.107Z [INFO]  raft: starting snapshot up to: index=37744
2021-07-22T14:46:48.107Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/2-37744-1626965208107.tmp
2021-07-22T14:47:05.462Z [INFO]  snapshot: reaping snapshot: path=/node/snapshots/2-12645-1626963010603
[store] 2021/07/22 14:47:05 snapshot and persist took 17.999509927s
2021-07-22T14:47:05.464Z [INFO]  raft: compacting logs: from=9939 to=22577
2021-07-22T14:47:05.553Z [INFO]  raft: snapshot complete up to: index=37744
[store] 2021/07/22 15:05:52 node snapshot created in 639.854742ms
2021-07-22T15:05:52.615Z [INFO]  raft: starting snapshot up to: index=50184
2021-07-22T15:05:52.615Z [INFO]  snapshot: creating new snapshot: path=/node/snapshots/2-50184-1626966352615.tmp
2021-07-22T15:06:14.086Z [INFO]  snapshot: reaping snapshot: path=/node/snapshots/2-25150-1626964175408
[store] 2021/07/22 15:06:14 snapshot and persist took 22.115448468s
2021-07-22T15:06:14.091Z [INFO]  raft: compacting logs: from=22578 to=35036
2021-07-22T15:06:14.145Z [INFO]  raft: snapshot complete up to: index=50184
panic: interface conversion: driver.Stmt is nil, not *sqlite3.SQLiteStmt

goroutine 25 [running]:
github.com/rqlite/go-sqlite3.(*SQLiteConn).exec(0xc00018ea20, 0xddbb00, 0xc00002e0a0, 0xc00024bc00, 0x6a8, 0x1414c70, 0x0, 0x0, 0xc000379920, 0x47b8bb, ...)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:803 +0x72e
github.com/rqlite/go-sqlite3.(*SQLiteConn).Exec(0xc00018ea20, 0xc00024bc00, 0x6a8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/rqlite/go-sqlite3@v1.20.2/sqlite3.go:792 +0x145
github.com/rqlite/rqlite/db.(*DB).Execute.func1(0xc000379ab0, 0xcfd300, 0xc0001914d0, 0xc000226000, 0x201, 0x0, 0x0)
	/tmp/tmp.xoS5K1RUKH/src/github.com/rqlite/rqlite/db/db.go:321 +0x2aa
github.com/rqlite/rqlite/db.(*DB).Execute(0xc0001914d0, 0xc000226000, 0xc000ef6101, 0x0, 0x0, 0x0, 0x0, 0xc0001f83f0)
	/tmp/tmp.xoS5K1RUKH/src/github.com/rqlite/rqlite/db/db.go:356 +0xa5
github.com/rqlite/rqlite/store.(*Store).Apply(0xc000182780, 0xc000460060, 0x0, 0x0)
	/tmp/tmp.xoS5K1RUKH/src/github.com/rqlite/rqlite/store/store.go:950 +0x3c6
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0019a8040)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:90 +0x2bd
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc00028a200, 0x1, 0x40)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc0002b6000)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/fsm.go:216 +0x3c4
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0002b6000, 0xc000194cd0)
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.xoS5K1RUKH/pkg/mod/github.com/hashicorp/raft@v1.3.0/state.go:144 +0x66
```

**Comment by otoolep** [comment] 2021-07-22 16:28
This is bizarre, I've filed an issue with the maintainers of the SQLite layer, linked above.

**Comment by Theog75** [comment] 2021-07-22 16:29
thanks!

**Comment by otoolep** [comment] 2021-07-22 16:58
@Theog75 @Dorsosiv -- let me see if I understand the sequence here.

You have an existing leader, and that leader is clearly receiving write traffic (`INSERT` and `UPDATE`) at a fairly high rate. You bring up another node (this one) and tell it to join. It joins. It runs for about 1.5 hours, and then crashes. Is that it, in this case?

**Comment by otoolep** [comment] 2021-07-22 17:12
I'm running a 2-node test that executes the scenario described above. Let's see if I can get it to crash.

**Comment by otoolep** [comment] 2021-07-22 18:23
@Theog75 @Dorsosiv -- are you doing any queries i.e. `SELECT` to the node that crashes? If so, what read consistency do you use? Also, are you using the transaction `transaction` flag at all in the URL?

**Comment by Theog75** [comment] 2021-07-22 19:25
after a whlie it was stables, when trying to query one of the members this is the response:
```
/rqlite -H rqlite-2.rqlite    
Welcome to the rqlite CLI. Enter ".help" for usage hints.
Version v6.0.1, commit b9b11db1aa49e4a2b9661c633ff4e4d3f961f526, branch master
Connected to rqlited version v6.0.1
rqlite-2.rqlite:4001> .tables
ERR! server responded with 503 Service Unavailable: not leader
```

**Comment by otoolep** [comment] 2021-07-22 19:48
It's hard to know what is going on there, I need more information. 

We can focus on the panic now. I suspect there is a race condition in the code, and you're hitting it because I think some query you're sending is also causing SQLite to hit an error. I have an idea, but it's going to take me a few days to put in a potential fix. I need to think about it. But what I have in mind should improve it.

What do you do when the node crashes? Just try again?

**Comment by otoolep** [comment] 2021-07-22 21:54
@Theog75 @Dorsosiv -- some interesting discussions in https://github.com/mattn/go-sqlite3/issues/959

Looks like you guys might have found a deep bug in rqlite, a bug that has been there for years. :-) Not 100% that we know the issue, but it's hard to believe it's not inproper handling of the database connection is the cause.

Fortunately the fix is clear, but it's going to take a few days to a couple of weeks to put in. I might be able to make some quick hacks, but can you manage for now?

**Comment by otoolep** [comment] 2021-07-23 05:49
@Theog75 @Dorsosiv -- **can you guys build master and run that?** I just committed a simple change which I believe will address this issue, at the cost of blocking concurrent reads. Reads will now be strictly serialized at the database level. Writes were always serialized.

Can  you try the latest code, and let me know if you see any more issues? I would guess if you run for a couple of weeks without the panic, the problem is solved. I can then work on a more sophisticated solution that will possibly bring concurrent read support back.

**Comment by otoolep** [comment] 2021-07-23 05:55
This is the change you should include in your build, which you will get by building HEAD: https://github.com/rqlite/rqlite/pull/834

**Comment by Theog75** [comment] 2021-07-23 09:03
@Dorsosiv will deploy it in our envs - with the rate we deal with data with the rqlites I guess a day will suffice to establish a stable version. regarding our deployment - due to the fact we use a cluster of 5 rqlites most of the time the DB service is continuous and DB access is available but there are times we have no database access until the rqlites are restarted (due to liveness probe failing) and they go back up in a normal manner.

@Dorsosiv lets test this version on one of our envs and report back to @otoolep .


Thanks again for the quick response !

**Comment by otoolep** [comment] 2021-07-23 13:22
@Theog75 @Dorsosiv -- one thing I want to make clear. The current theory for this issue is the following:

1. A write request (`INSERT` or `UPDATE` for example) is sent to your rqlite system at some point.
2. SQLite raises an error when it encounters this particular request
3. This error was not handled properly by the rest of rqlite, and the node crashed.

The latest change should address point #3 only. So you should still be on the lookout for an error response coming back from rqlite, for one of your write requests. It will be interesting to see what that is, assuming we see one.

**Comment by otoolep** [comment] 2021-07-27 12:26
@Theog75 @Dorsosiv  -- I presume it's still running? Any sign of anything not working right? I'll let you guys run it for another week or so, and then I'll start working on a more comprehensive solution to this issue, assuming the current software continues to run OK.

**Comment by otoolep** [comment] 2021-07-30 15:31
Hey @Theog75 @Dorsosiv - any update? I'll shortly release a new version (6.0.2) with a better fix for this issue, assuming we do know what the root cause is of this issue.

**Comment by otoolep** [comment] 2021-07-31 17:23
@Theog75 @Dorsosiv -- I believe this is fixed in version 6.0.2, which has been released. Please be sure to run 6.0.2, or later, going forward.

**Closed by otoolep** 2021-07-31 17:23 UTC

**Comment by Dorsosiv** [comment] 2021-08-08 07:31
Hey @otoolep sorry for not responding. We'll try the release-6.0.2 of rqlite and hopefully the issue is resolved.

**Comment by otoolep** [comment] 2021-08-08 13:21
Actually, you should run 6.1.0 now.
