### ISSUE TITLE
concatenating issues in select statements

### ISSUE THREAD

**Issue by gilwo** [rqlite/rqlite#240] opened 2016-12-20 14:58 UTC
following the example of the insertion in the main rqlite readme:

```
12 ~ curl -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
>     "CREATE TABLE foo (id integer not null primary key, name text)"
> ]'
```
resulted in 
```
{
    "results": [
        {
            "time": 0.0008569220000000001
        }
    ],
    "time": 0.0015574340000000001
}
```
then adding some data 

```
13 ~ curl -XPOST 'localhost:4001/db/execute?pretty&timings' -H "Content-Type: application/json" -d '[
>     "INSERT INTO foo(name) VALUES(\"fiona\")"
> ]'
```
resulting in 
```
{
    "results": [
        {
            "last_insert_id": 1,
            "rows_affected": 1,
            "time": 0.000112929
        }
    ],
    "time": 0.00865072
}
```
then querying data in a specific template :
```
14 ~ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=SELECT id || "_bar", name FROM foo'
```
resulting in 
```
{
    "results": [
        {
            "columns": [
                "id || \"_bar\"",
                "name"
            ],
            "types": [
                "",
                "text"
            ],
            "values": [
                [
                    "MV9iYXI=",
                    "fiona"
                ]
            ],
            "time": 0.00012579800000000002
        }
    ],
    "time": 0.00016618200000000002
}
```
values fields in the location of the concatenated value is malformed or encoded in something unfamiliar.
is it encoded ? seems like something is wrong, column definition isnt looking so good.

trying again this time with column specific name
```
15 ~ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=SELECT id || "_bar" as ID, name FROM foo'
```
resulting in :
```
{
    "results": [
        {
            "columns": [
                "ID",
                "name"
            ],
            "types": [
                "",
                "text"
            ],
            "values": [
                [
                    "MV9iYXI=",
                    "fiona"
                ]
            ],
            "time": 0.000194018
        }
    ],
    "time": 0.00024893800000000003
}
```
now trying some text manipulation 
```
16 ~ curl -G 'localhost:4001/db/query?pretty&timings' --data-urlencode 'q=SELECT id || \"_bar\" as ID, name FROM foo'
```
result in 
```
{
    "results": [
        {
            "error": "unrecognized token: \"\\\""
        }
    ],
    "time": 5.516600000000001e-05
}
```

**Comment by otoolep** [comment] 2016-12-20 15:13
Thanks @gilwo for the report, rqlite doesn't look like it's doing the right thing, as you say. Using straight SQLite works fine:
```
sqlite> CREATE TABLE foo (id integer not null primary key, name text);
sqlite> INSERT INTO foo(name) VALUES("fiona");
sqlite> SELECT id,name FROM foo;
1|fiona
sqlite> SELECT id || "_bar", name FROM foo;
1_bar|fiona
```
This may be solved by full handling of the underlying types -- I've actually started that work in https://github.com/rqlite/rqlite/pull/221, but that work stalled. Looks like I need to return to it ASAP.

**Comment by otoolep** [comment] 2016-12-20 15:25
https://github.com/rqlite/rqlite/pull/221 has now been updated so it handles this situation correctly. I need to do more research before merging it, as it may be a hack. I don't know for sure yet.

@gilwo -- you could try building the `handle_sqlite_datatypes` branch, since the issue is practically addressed there.

**Comment by gilwo** [comment] 2016-12-21 15:32
thanks for the prompt response, i have some issues to build rqlite.
I dont really understand how to build rqlite at all let alone that specific branch.
i am really novice in go and i dont understand whats going on behind the scenes.
i tried to figure out from the posts around on how to build it but i got confused.
can you shed some light on the build process ? i am trying to build it on my linux machine running ubuntu 14.04 LTS.
thanks

**Comment by otoolep** [comment] 2016-12-21 23:24
Fixed by https://github.com/rqlite/rqlite/issues/240

**Comment by otoolep** [comment] 2016-12-21 23:26
@gilwo -- I suggest you read https://github.com/rqlite/rqlite/blob/master/CONTRIBUTING.md#building-rqlite which has full details on building rqlite. If you build master you should have a binary that addresses this issue. Otherwise you'll have to wait until the next release.

**Comment by otoolep** [comment] 2016-12-21 23:27
@gilwo -- I would be interested if you have any problems following the build instructions. They are meant to be foolproof.

**Closed by otoolep** 2016-12-21 23:26 UTC

**Comment by gilwo** [comment] 2016-12-22 12:45
thanks for the reference, i tested it and it seems to work nicely for my current use
