### ISSUE TITLE
Build from source fails in Windows VM

### ISSUE THREAD

**Issue by LuKks** [rqlite/rqlite#1763] opened 2024-04-27 03:28 UTC
**Are you using Docker or Kubernetes to run your system?**

It's a virtual machine with Windows 10 (22H2), and the Go version is 1.22.2/amd64. The host is Ubuntu 24.04

**What did you do?**

I ran the exact same commands from https://rqlite.io/docs/install-rqlite/building-from-source/

**What happened instead?**

The `go install ./...` step fails to generate the `rqlited` binary

```
...
go: downloading golang.org/x/text v0.3.8
go: downloading github.com/jmespath/go-jmespath v0.4.0
# github.com/rqlite/rqlite/v8/db
db\db.go:84:28: undefined: sqlite3.Version
db\db.go:1225:21: c.Prepare undefined (type *sqlite3.SQLiteConn has no field or method Prepare)
db\db.go:1335:17: dst.Backup undefined (type *sqlite3.SQLiteConn has no field or method Backup)
```

`ls $GOPATH/bin`

```
rqbench.exe*  rqlite.exe*  walr.exe*
```

**Comment by otoolep** [comment] 2024-04-27 12:03
@LuKks -- you can see successful Windows build here: https://ci.appveyor.com/project/otoolep/rqlite

@dwco-z -- you build on Windows. Do you do anything special, beyond the docs at https://rqlite.io/docs/install-rqlite/building-from-source/

**Comment by otoolep** [comment] 2024-04-27 14:49
@LuKks -- do you have a C compiler installed, and is `CGO_ENABLED=1` set?

**Comment by otoolep** [comment] 2024-04-27 14:52
Because what you are seeing implies it is not. I can reproduce your build errors like this:
```bash
$ CGO_ENABLED=0 go build .
# github.com/rqlite/rqlite/v8/db
../../db/db.go:84:28: undefined: sqlite3.Version
../../db/db.go:1225:21: c.Prepare undefined (type *sqlite3.SQLiteConn has no field or method Prepare)
../../db/db.go:1335:17: dst.Backup undefined (type *sqlite3.SQLiteConn has no field or method Backup)
```

See https://github.com/mattn/go-sqlite3?tab=readme-ov-file#compilation

**Comment by otoolep** [comment] 2024-04-27 15:05
I've updated the build documentation to make this clearer: 

https://rqlite.io/docs/install-rqlite/building-from-source/#compilation-errors-locating-sqlite-functions

I can leave this issue open, but may close it soon. I'm pretty sure you just need to make sure you have a C compiler installed.

**Comment by LuKks** [comment] 2024-04-27 21:49
Thanks! `CGO_ENABLED=1` plus installing `gcc` via https://jmeubank.github.io/tdm-gcc did it!

**Comment by LuKks** [comment] 2024-04-27 21:51
In case someone wants to easily install it anywhere: https://github.com/like/rqlite-runtime

`npm i -g rqlite`

Then just `rqlited ./data1` or `rqilte`

I'm missing builds for macOS x64 and Raspberry Pi but will look into it when I find some machines for that

**Comment by LuKks** [comment] 2024-04-27 21:54
There is also a new tiny and simple Node.js wrapper in the works but private atm until it's complete, excited for that!

**Closed** 2024-04-28 16:21 UTC
