### ISSUE TITLE
docker-compose started instance heartbeat timeout

### ISSUE THREAD

**Issue by nickarls** [rqlite/rqlite#1289] opened 2023-06-01 10:39 UTC
if I start a single-node instance with docker run, it works fine.
If I start it through docker-compose, the heartbeat times out and the node is not elected leader, resulting in a 503 for queries

```
2023-06-01T10:33:46.598Z [INFO]  raft: entering follower state: follower="Node at 9a7f5b17f46b:4002 [Follower]" leader-address= leader-id=
2023-06-01T10:33:47.963Z [WARN]  raft: heartbeat timeout reached, not part of a stable configuration or a non-voter, not triggering a leader election
```

The stack is pretty much
```
  rqlite:
    container_name: rqlite
    image: rqlite/rqlite
    ports:
      - 4001:4001
    restart: always
    volumes:
      - rqlite-data:/rqlite/file/data
```

**Comment by otoolep** [comment] 2023-06-01 10:51
"pretty much" might be doing a lot of work here. :-)

It's hard to tell what is going on, with such little information. I'll need much more than this to repro what you are seeing. You haven't told me what version you're running, if you built the container yourself, any special network configuration, the `/status` and diagnostics out, and so on. I also need the full logs from both the successful run, and the failed run.

My best guess is that rqlite is picking up some pre-existing state when you start with `docker compose` that conflicts with the state it sees it is restarted with Docker Compose. My guess is that it's the node ID, which defaults to the hostname if not set (at least in the Docker containers I release) -- and the hostname is changing between runs. Check for this line in the logs:
```
[store] 2023/06/01 06:48:33 opening store with node ID localhost:4002
```
and see if it's changing between runs.

If so you need to either a) explicitly set the hostname to the same value, or b) set the node ID at launch time.

**Comment by otoolep** [comment] 2023-06-01 10:52
Corrected comment.

**Comment by otoolep** [comment] 2023-06-01 10:55
https://github.com/rqlite/rqlite-docker/blob/master/7.20.0/docker-entrypoint.sh#L15 is where the Docker containers I release set the hostname. If the hostname changes between restarts, it will change the node ID (unless you set it) and will cause this problem.

**Comment by nickarls** [comment] 2023-06-01 12:22
Indeed a good candidate - commenting out the volumes works, I'll do some further research on the host name and state restore. Thanks for the starting point

**Comment by otoolep** [comment] 2023-06-01 12:59
I'm not a Docker expert, so don't know a huge amount, but rqlite runs very well on Kubernetes via Stateful sets. rqlite is a stateful application, which generally needs persistent storage, networking, and some other state, for reliable operation. Perhaps there is something similar in your environment.

https://rqlite.io/docs/guides/kubernetes/

That said, you're not the first person to use Docker Compose with rqlite. If you get it to work, and believe you're following best practices, I would be interested in adding a new doc about using Compose to rqlite.io.

**Comment by otoolep** [comment] 2023-06-02 14:08
I'm going to close this, since rqlite is working as intended. Please report back if you learn anything about the right way to use Compose with rqlite.

**Closed by otoolep** 2023-06-02 14:08 UTC
