### ISSUE TITLE
rqlited 5.10.2 cluster on k8s crashed

### ISSUE THREAD

**Issue by Theog75** [rqlite/rqlite#781] opened 2021-04-09 07:49 UTC
version 5.10.2

5 rqlite servers cluster

env : K8s 1.20

debug output:

```
            _ _ _
           | (_) |
  _ __ __ _| |_| |_ ___
 | '__/ _  | | | __/ _ \   The lightweight, distributed
 | | | (_| | | | ||  __/   relational database.
 |_|  \__, |_|_|\__\___|
         | |               www.rqlite.com
         |_|

[rqlited] 2021/04/09 07:44:05 rqlited starting, version v5.10.2, commit 125ae547879fc5a5b2cbb672b8f5011c171e5907, branch master
[rqlited] 2021/04/09 07:44:05 go1.15, target architecture is amd64, operating system target is linux
[rqlited] 2021/04/09 07:44:05 launch command: /rqlited -node-id rqlite-3 -raft-snap 4096 -raft-timeout 4s -raft-leader-lease-timeout 3s -raft-election-timeout 5s -http-addr rqlite-3.rqlite:4001 -raft-addr rqlite-3.rqlite:4002 /node
[rqlited] 2021/04/09 07:44:05 no preexisting node state detected in /node, node may be bootstrapping
[rqlited] 2021/04/09 07:44:05 no join addresses set
[store] 2021/04/09 07:44:05 opening store with node ID rqlite-3
[store] 2021/04/09 07:44:05 ensuring directory at /node exists
[store] 2021/04/09 07:44:05 0 preexisting snapshots present
[store] 2021/04/09 07:44:05 first log index: 0, last log index: 0, last command log index: 0:
2021-04-09T07:44:05.861Z [INFO]  raft: initial configuration: index=0 servers=[]
[store] 2021/04/09 07:44:05 executing new cluster bootstrap
2021-04-09T07:44:05.861Z [INFO]  raft: entering follower state: follower="Node at 10.129.6.20:4002 [Follower]" leader=
2021-04-09T07:44:13.849Z [WARN]  raft: heartbeat timeout reached, starting election: last-leader=
2021-04-09T07:44:13.849Z [INFO]  raft: entering candidate state: node="Node at 10.129.6.20:4002 [Candidate]" term=2
2021-04-09T07:44:13.933Z [INFO]  raft: election won: tally=1
2021-04-09T07:44:13.933Z [INFO]  raft: entering leader state: leader="Node at 10.129.6.20:4002 [Leader]"
[store] 2021/04/09 07:44:13 waiting for up to 2m0s for application of initial logs
[http] 2021/04/09 07:44:14 service listening on 10.129.6.20:4001
[rqlited] 2021/04/09 07:44:14 node is ready
[rqlited] 2021/04/09 07:45:00 http: panic serving 10.128.7.123:44710: interface conversion: interface {} is nil, not *store.fsmExecuteResponse
goroutine 530 [running]:
net/http.(*conn).serve.func1(0xc000292460)
	/home/philip/.gvm/gos/go1.15/src/net/http/server.go:1801 +0x147
panic(0xbf3f80, 0xc0003ddd70)
	/home/philip/.gvm/gos/go1.15/src/runtime/panic.go:975 +0x3e9
github.com/rqlite/rqlite/store.(*Store).execute(0xc00008da00, 0xc0004f4300, 0x41c878, 0x50, 0xc57ee0, 0xc000298901, 0xc0003506e0)
	/tmp/tmp.rOi1r2qzkt/src/github.com/rqlite/rqlite/store/store.go:591 +0x4a9
github.com/rqlite/rqlite/store.(*Store).Execute(0xc00008da00, 0xc0004f4300, 0x200, 0xc0002180f8, 0x1, 0x1, 0x0)
	/tmp/tmp.rOi1r2qzkt/src/github.com/rqlite/rqlite/store/store.go:536 +0x78
github.com/rqlite/rqlite/http.(*Service).handleExecute(0xc000280a80, 0xdb1ba0, 0xc0006be2a0, 0xc0004d2500)
	/tmp/tmp.rOi1r2qzkt/src/github.com/rqlite/rqlite/http/service.go:642 +0x437
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc000280a80, 0xdb1ba0, 0xc0006be2a0, 0xc0004d2500)
	/tmp/tmp.rOi1r2qzkt/src/github.com/rqlite/rqlite/http/service.go:250 +0x5df
net/http.serverHandler.ServeHTTP(0xc000280b60, 0xdb1ba0, 0xc0006be2a0, 0xc0004d2500)
	/home/philip/.gvm/gos/go1.15/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc000292460, 0xdb3860, 0xc00019c080)
	/home/philip/.gvm/gos/go1.15/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.15/src/net/http/server.go:2969 +0x36c
panic: failed to unmarshal execute subcommand: unexpected EOF

goroutine 13 [running]:
github.com/rqlite/rqlite/store.(*Store).Apply(0xc00008da00, 0xc000111a68, 0x0, 0x0)
	/tmp/tmp.rOi1r2qzkt/src/github.com/rqlite/rqlite/store/store.go:1042 +0xc0b
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc000195c20)
	/tmp/tmp.rOi1r2qzkt/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:90 +0x2c2
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc000372200, 0x1, 0x40)
	/tmp/tmp.rOi1r2qzkt/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc00028a000)
	/tmp/tmp.rOi1r2qzkt/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:219 +0x3c4
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc00028a000, 0xc000126c90)
	/tmp/tmp.rOi1r2qzkt/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.rOi1r2qzkt/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:144 +0x66

```

**Comment by Theog75** [comment] 2021-04-09 08:20
btw - the issue does not happen in V5.5.1 - reverted to v5.5.1 for now

**Comment by otoolep** [comment] 2021-04-09 11:53
Thanks for your report. Can you provide details on how you cause this? Can you reproduce on demand? What sequence of queries do you send?

**Comment by otoolep** [comment] 2021-04-09 12:50
@Theog75 -- this looks like it happens on startup, with the data that is currently on your node. Would you be prepared to share your data directory with me? Zip it up and attach to this bug? Or email it to me?

**Comment by otoolep** [comment] 2021-04-09 12:53
Actually, from your log this looks like the startup of a brand new node. Is that correct?

**Comment by otoolep** [comment] 2021-04-09 12:57
So this is what your log implies:

- you start a brand new node, with no preexisting data set.
- this single node becomes leader
- the node attempts to apply a single change to the database, a command which was sent by you to the the `/db/execute` endpoint. This is because this crash is at [this line](https://github.com/rqlite/rqlite/blob/v5.10.2/store/store.go#L591), in a function which only executes in response to a HTTP request made by you.
- that change is handled incorrectly, and the software panics.

Can you share that HTTP request you made, which causes this node to panic?

**Comment by Theog75** [comment] 2021-04-09 20:31
this actually happened upon restarting the cluster - I can share our deployment and it is possible to change the rqlite version with which the pods are running.
- v5.5.1 works perfectly
- v5.10.2 starts and crashes after a few seconds.
yes there is data is the other pods (an auto healing script is actually restarting the cluster upon quorum lost) .

should I post our deployment?

**Comment by otoolep** [comment] 2021-04-09 21:00
Yes, please post anything you think is valuable. However I just want to point out that the panic clearly shows a HTTP request being sent to that node. This line is in the trace:

https://github.com/rqlite/rqlite/blob/v5.10.2/http/service.go#L250

That line is the HTTP handler for the `db/execute` endpoint. Do you have any idea what that request is?

**Comment by Dorsosiv** [comment] 2021-04-12 10:33
Hello this the deployment we use when we run the rqlite as a cluster. 

[rqlite.txt](https://github.com/rqlite/rqlite/files/6295855/rqlite.txt)

**Comment by otoolep** [comment] 2021-04-12 12:08
Can you show me the HTTP traffic that is sent to this node? As per the comment above, it's receiving a HTTP execute request that causes it to crash. If I could see that request, I'm sure I could fix this issue.

**Comment by otoolep** [comment] 2021-04-12 19:22
Actually, I think I may be misreading your log. I think I see what the issue might really be.

Are you upgrading from a 5.5.1 cluster to 5.10.2? 5.10.2 is supposed to fix handle upgrades automatically, but there may be a bug in the conversion logic, such that you're hitting a corner case in moving from 5.5.1 to 5.10.2. To fix this issue I would probably need a copy of the data directory that is sitting under a node, so I could reproduce this issue.

If you don't want to do this, and just get 5.10.2 working, you can do this following:

- backup a node on your cluster, by dumping the contents to SQL. see https://github.com/rqlite/rqlite/blob/master/DOC/BACKUPS.md
- Provision a brand new 5.10.2 cluster
- play the SQL commands back into that cluster. See https://github.com/rqlite/rqlite/blob/master/DOC/RESTORE_FROM_SQLITE.md

This will avoid the upgrade path from 5.5.1 to 5.10.2, which looks buggy in your case.

**Comment by otoolep** [comment] 2021-04-12 21:25
I just released 5.11.0. Can you try that version, and show me what happens? I'd like to see the log, just like your original post.

**Comment by Dorsosiv** [comment] 2021-04-13 12:34
Hey, a few things that you should know. 

we deploy rqlite as a new instance when it dies. so no need to keep data.

when we change versions of rqlite we change redeploy the instances and it runs. we do not upgrade existing instances, we replace them.

About rqlite 5.11.0 we have tried it and we received the following logs : 

```
2021-04-13T09:03:34.944Z [INFO]  raft: added peer, starting replication: peer=rqlite-2
2021-04-13T09:03:35.038Z [WARN]  raft: appendEntries rejected, sending older logs: peer="{Voter rqlite-2 10.233.88.50:4002}" next=1
2021-04-13T09:03:35.335Z [INFO]  raft: pipelining replication: peer="{Voter rqlite-2 10.233.88.50:4002}"
[store] 2021/04/13 09:03:35 node at 10.233.88.50:4002 joined successfully as voter
[rqlited] 2021/04/13 09:03:35 http: panic serving 10.233.122.46:37928: index > windowEnd
goroutine 81 [running]:
net/http.(*conn).serve.func1(0xc0000d83c0)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:1801 +0x147
panic(0xbbde00, 0xd91920)
	/home/philip/.gvm/gos/go1.15.7/src/runtime/panic.go:975 +0x47a
compress/flate.(*compressor).deflate(0xc000400000)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:397 +0xa25
compress/flate.(*compressor).write(0xc000400000, 0xc000940000, 0x5100e, 0x1100e, 0x5100e, 0x75d50bb6, 0x0)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:554 +0x85
compress/flate.(*Writer).Write(...)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:712
compress/gzip.(*Writer).Write(0xc0000cc000, 0xc000900000, 0x5100e, 0x5100e, 0xc0001c8180, 0x0, 0xc000900000)
	/home/philip/.gvm/gos/go1.15.7/src/compress/gzip/gzip.go:196 +0xc5
github.com/rqlite/rqlite/command.(*RequestMarshaler).Marshal(0xc0000a00e0, 0xdb4200, 0xc0001c8180, 0xc0000a7ac0, 0xa95445, 0x203000, 0x203000, 0x203000, 0xc000022a80)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/command/marshal.go:102 +0x20a
github.com/rqlite/rqlite/store.(*Store).execute(0xc0000ce000, 0xc0001c8180, 0x41c8b8, 0x50, 0xc593e0, 0xc000122001, 0xc0005ac5f0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/store/store.go:562 +0x5d
github.com/rqlite/rqlite/store.(*Store).Execute(0xc0000ce000, 0xc0001c8180, 0x7fe00, 0xc000022a80, 0x146, 0x146, 0x0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/store/store.go:536 +0x78
github.com/rqlite/rqlite/http.(*Service).handleExecute(0xc000134380, 0xdb2200, 0xc000020540, 0xc0001d8600)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/http/service.go:642 +0x437
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc000134380, 0xdb2200, 0xc000020540, 0xc0001d8600)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/http/service.go:250 +0x5df
net/http.serverHandler.ServeHTTP(0xc000134460, 0xdb2200, 0xc000020540, 0xc0001d8600)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0000d83c0, 0xdb3f00, 0xc000312000)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:2969 +0x36c
[store] 2021/04/13 09:03:38 received request to join node at 10.233.116.89:4002

```

```
2021-04-13T09:03:59.422Z [WARN]  raft: Election timeout reached, restarting election
2021-04-13T09:03:59.423Z [INFO]  raft: entering candidate state: node="Node at 10.233.77.210:4002 [Candidate]" term=5
2021-04-13T09:04:03.172Z [INFO]  raft: duplicate requestVote for same term: term=5
2021-04-13T09:04:03.364Z [INFO]  raft: election won: tally=3
2021-04-13T09:04:03.364Z [INFO]  raft: entering leader state: leader="Node at 10.233.77.210:4002 [Leader]"
2021-04-13T09:04:03.364Z [INFO]  raft: added peer, starting replication: peer=rqlite-2
2021-04-13T09:04:03.364Z [INFO]  raft: added peer, starting replication: peer=rqlite-3
2021-04-13T09:04:03.364Z [INFO]  raft: added peer, starting replication: peer=rqlite-0
2021-04-13T09:04:03.366Z [WARN]  raft: appendEntries rejected, sending older logs: peer="{Voter rqlite-2 10.233.88.50:4002}" next=172
2021-04-13T09:04:03.368Z [INFO]  raft: pipelining replication: peer="{Voter rqlite-0 10.233.122.238:4002}"
2021-04-13T09:04:03.388Z [WARN]  raft: appendEntries rejected, sending older logs: peer="{Voter rqlite-3 10.233.116.89:4002}" next=155
2021-04-13T09:04:03.406Z [INFO]  raft: pipelining replication: peer="{Voter rqlite-3 10.233.116.89:4002}"
2021-04-13T09:04:03.517Z [INFO]  raft: pipelining replication: peer="{Voter rqlite-2 10.233.88.50:4002}"
[rqlited] 2021/04/13 09:04:12 http: panic serving 10.233.91.86:39794: index > windowEnd
goroutine 1030 [running]:
net/http.(*conn).serve.func1(0xc0006292c0)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:1801 +0x147
panic(0xbbde00, 0xd91920)
	/home/philip/.gvm/gos/go1.15.7/src/runtime/panic.go:975 +0x47a
compress/flate.(*compressor).deflate(0xc000400000)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:397 +0xa25
compress/flate.(*compressor).write(0xc000400000, 0xc0001f0000, 0x1c01, 0x1c01, 0x1c01, 0xe14967bd, 0x0)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:554 +0x85
compress/flate.(*Writer).Write(...)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:712
compress/gzip.(*Writer).Write(0xc0000cc000, 0xc0001f0000, 0x1c01, 0x1c01, 0xc00002f4c0, 0x0, 0xc0001f0000)
	/home/philip/.gvm/gos/go1.15.7/src/compress/gzip/gzip.go:196 +0xc5
github.com/rqlite/rqlite/command.(*RequestMarshaler).Marshal(0xc0000a00e0, 0xdb4200, 0xc00002f4c0, 0xc0001e9ac0, 0xa95445, 0x203000, 0x203000, 0x203000, 0xc0004f0420)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/command/marshal.go:102 +0x20a
github.com/rqlite/rqlite/store.(*Store).execute(0xc0000ce000, 0xc00002f4c0, 0x41c8b8, 0x50, 0xc593e0, 0xc0000a0601, 0xc0006deaf0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/store/store.go:562 +0x5d
github.com/rqlite/rqlite/store.(*Store).Execute(0xc0000ce000, 0xc00002f4c0, 0x1e00, 0xc0004f0420, 0xb, 0xb, 0x0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/store/store.go:536 +0x78
github.com/rqlite/rqlite/http.(*Service).handleExecute(0xc000134380, 0xdb2200, 0xc000134540, 0xc000316300)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/http/service.go:642 +0x437
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc000134380, 0xdb2200, 0xc000134540, 0xc000316300)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/http/service.go:250 +0x5df
net/http.serverHandler.ServeHTTP(0xc000134460, 0xdb2200, 0xc000134540, 0xc000316300)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0006292c0, 0xdb3f00, 0xc000619580)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:2969 +0x36c
[rqlited] 2021/04/13 09:04:12 http: panic serving 10.233.101.173:48512: index > windowEnd
goroutine 583 [running]:
net/http.(*conn).serve.func1(0xc0001a3400)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:1801 +0x147
panic(0xbbde00, 0xd91920)
	/home/philip/.gvm/gos/go1.15.7/src/runtime/panic.go:975 +0x47a
compress/flate.(*compressor).deflate(0xc000400000)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:397 +0xa25
compress/flate.(*compressor).close(0xc000400000, 0xc00021a000, 0x1bed)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:646 +0x50
compress/flate.(*Writer).Close(...)
	/home/philip/.gvm/gos/go1.15.7/src/compress/flate/deflate.go:732
compress/gzip.(*Writer).Close(0xc0000cc000, 0xc00021a000, 0x1bed)
	/home/philip/.gvm/gos/go1.15.7/src/compress/gzip/gzip.go:242 +0x6a
github.com/rqlite/rqlite/command.(*RequestMarshaler).Marshal(0xc0000a00e0, 0xdb4200, 0xc0001c8640, 0xc0001e3ac0, 0xa95445, 0x203000, 0x203000, 0x203000, 0xc00053f7a0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/command/marshal.go:105 +0x232
github.com/rqlite/rqlite/store.(*Store).execute(0xc0000ce000, 0xc0001c8640, 0x41c8b8, 0x50, 0xc593e0, 0xc0006d8501, 0xc0001014a0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/store/store.go:562 +0x5d
github.com/rqlite/rqlite/store.(*Store).Execute(0xc0000ce000, 0xc0001c8640, 0x1e00, 0xc00053f7a0, 0xb, 0xb, 0x0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/store/store.go:536 +0x78
github.com/rqlite/rqlite/http.(*Service).handleExecute(0xc000134380, 0xdb2200, 0xc000020380, 0xc000190100)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/http/service.go:642 +0x437
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc000134380, 0xdb2200, 0xc000020380, 0xc000190100)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/http/service.go:250 +0x5df
net/http.serverHandler.ServeHTTP(0xc000134460, 0xdb2200, 0xc000020380, 0xc000190100)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:2843 +0xa3
net/http.(*conn).serve(0xc0001a3400, 0xdb3f00, 0xc0003c6400)
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:1925 +0x8ad
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.15.7/src/net/http/server.go:2969 +0x36c
2021-04-13T09:04:12.947Z [WARN]  raft: failed to contact: server-id=rqlite-0 time=501.036942ms
2021-04-13T09:04:13.396Z [WARN]  raft: failed to contact: server-id=rqlite-0 time=950.042204ms
2021-04-13T09:04:13.842Z [WARN]  raft: failed to contact: server-id=rqlite-0 time=1.395985525s
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x8bdfad]
goroutine 36 [running]:
github.com/rqlite/rqlite/db.(*DB).Execute(0xc0000908d0, 0x0, 0xc000618000, 0x0, 0x0, 0x0, 0x0, 0x0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/db/db.go:249 +0x2d
github.com/rqlite/rqlite/store.(*Store).Apply(0xc0000ce000, 0xc000754de8, 0x0, 0x0)
	/tmp/tmp.WGoiA4PHIW/src/github.com/rqlite/rqlite/store/store.go:1044 +0x36c
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0001b6090)
	/tmp/tmp.WGoiA4PHIW/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:90 +0x2c2
github.com/hashicorp/raft.(*Raft).runFSM.func2(0xc0004ec200, 0x4, 0x40)
	/tmp/tmp.WGoiA4PHIW/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:113 +0x75
github.com/hashicorp/raft.(*Raft).runFSM(0xc0000f8000)
	/tmp/tmp.WGoiA4PHIW/pkg/mod/github.com/hashicorp/raft@v1.2.0/fsm.go:219 +0x3c4
github.com/hashicorp/raft.(*raftState).goFunc.func1(0xc0000f8000, 0xc0000942f0)
	/tmp/tmp.WGoiA4PHIW/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:146 +0x55
created by github.com/hashicorp/raft.(*raftState).goFunc
	/tmp/tmp.WGoiA4PHIW/pkg/mod/github.com/hashicorp/raft@v1.2.0/state.go:144 +0x66
```

**Comment by otoolep** [comment] 2021-04-13 12:41
Thanks for the extra information.

What you are hitting are issues in the Go compression libraries. I'm not sure what could cause it, but a bug in the Go library is a possibility. I wonder if it's something about your environment -- I've seen another other report of this happening.

You are running the 5.11.0 Docker image? And that runs in Kubernetes, correct?

**Comment by otoolep** [comment] 2021-04-13 13:01
I think I see the issue, there was a race in the compression code.

**Comment by otoolep** [comment] 2021-04-13 14:33
Thanks so much for your reports on this issue -- it helped me find a pretty bad bug. I believe v5.11.1 addresses this issue (all reports you have filed were from panics in the compression/decompression code) so I'll close this issue. Please re-open if you see more panics.

**Comment by otoolep** [comment] 2021-04-13 14:33
https://github.com/rqlite/rqlite/releases/tag/v5.11.1

Docker image created too.

https://hub.docker.com/r/rqlite/rqlite/tags?page=1&ordering=last_updated

**Closed by otoolep** 2021-04-13 14:33 UTC

**Comment by Dorsosiv** [comment] 2021-04-13 15:07
> Thanks for the extra information.
> 
> What you are hitting are issues in the Go compression libraries. I'm not sure what could cause it, but a bug in the Go library is a possibility. I wonder if it's something about your environment -- I've seen another other report of this happening.
> 
> You are running the 5.11.0 Docker image? And that runs in Kubernetes, correct?

yeah

**Comment by Dorsosiv** [comment] 2021-04-13 15:13
@otoolep , something I did not understand,  did you fix that problem or should we wait for the next rqlite release ?

**Comment by otoolep** [comment] 2021-04-13 15:48
I believe the problem is fixed in 5.11.1, which has been released.

https://github.com/rqlite/rqlite/releases/tag/v5.11.1
https://hub.docker.com/r/rqlite/rqlite/tags?page=1&ordering=last_updated

`docker pull rqlite/rqlite` should pull down the latest image, which is 5.11.1.

**Comment by Dorsosiv** [comment] 2021-04-13 18:30
We'll download it and try it

**Comment by otoolep** [comment] 2021-04-15 13:26
@Dorsosiv -- are we good here? Is it working for you now?

**Comment by momoadc** [comment] 2021-04-15 15:08
Hi @otoolep I am testing it right now - will report back.

Thanks!
