### ISSUE TITLE
Too many open files (TCPv6 sockets?)

### ISSUE THREAD

**Issue by zhangyongding** [rqlite/rqlite#1866] opened 2024-08-20 13:24 UTC
**What version are you running?**

v8.23.0

**What Operating System are you running?**

Linux

**Are you using Docker or Kubernetes to run rqlite?**

No

**Are you running a single node or a cluster?**

cluster

**What did you do?**

Similar to this error, https://github.com/hashicorp/vault/issues/3244
At the same time, the usage of memory and CPU is much higher than normal.
I don't know how to reproduce it at the moment. Is it possible that a network anomaly caused the coroutines of HTTP or TCP ports to not be reclaimed, resulting in handle leakage.

**Comment by otoolep** [comment] 2024-08-20 13:32
Interesting, presumably rqlite shares the same Raft code as Vault since Vault is also a Hashicorp product. So this looks like a Raft issue, not a rqlite issue specifically.

If you can reproduce, the Hashicorp team could be quite interested. Can you?

**Comment by otoolep** [comment] 2024-08-31 16:47
Since this appears to be a Raft issue, and not a rqlite issue, I'm closing.

**Closed by otoolep** 2024-08-31 16:47 UTC
