### ISSUE TITLE
Issue with restore

### ISSUE THREAD

**Issue by jmordica** [rqlite/rqlite#1016] opened 2022-05-06 18:56 UTC
**What version are you running?**
7.3.2 on MacOS Macbook Pro M1 Pro and also Linux Ubuntu 20.04 single core CPU (same results)

I’ve learned a few things here based on trying different things. My testing was done with default startup and single node (sqlite in memory and raft log on disk) 7.3.2:
- rqlite doesn’t seem to like restores of any larger than ~15mb in file size. So under 10mb seems to be safe. Splitting inserts into ~10mb files gets the job done.
- Anything over ~15mb produces this log after ~4 min of waiting for the restore to finish (and the restore never actually completes):
```
[rqlited] 2022/05/05 22:12:07 http: panic serving 127.0.0.1:51783: runtime error: index out of range [0] with length 0
goroutine 192 [running]:
net/http.(*conn).serve.func1(0xc000310780)
	/usr/local/go/src/net/http/server.go:1804 +0x153
panic(0x4c41420, 0xc000396108)
	/usr/local/go/src/runtime/panic.go:971 +0x499
github.com/rqlite/rqlite/db.(*DB).memStats(0xc0003ba190, 0xc000312600, 0x2d, 0x2d)
	/var/folders/tm/97rx_rf519d6lkg48r5rvt700000gn/T/tmp.zmEGcHT0/src/github.com/rqlite/rqlite/db/db.go:804 +0x30d
github.com/rqlite/rqlite/db.(*DB).Stats(0xc0003ba190, 0x55, 0x203000, 0x1000)
	/var/folders/tm/97rx_rf519d6lkg48r5rvt700000gn/T/tmp.zmEGcHT0/src/github.com/rqlite/rqlite/db/db.go:264 +0x8a
github.com/rqlite/rqlite/store.(*Store).Stats(0xc0003c0000, 0xc000022100, 0x4cf05a4, 0x6)
	/var/folders/tm/97rx_rf519d6lkg48r5rvt700000gn/T/tmp.zmEGcHT0/src/github.com/rqlite/rqlite/store/store.go:643 +0x8a
github.com/rqlite/rqlite/http.(*Service).handleStatus(0xc0001940f0, 0x4e25650, 0xc00019a8c0, 0xc000022100)
	/var/folders/tm/97rx_rf519d6lkg48r5rvt700000gn/T/tmp.zmEGcHT0/src/github.com/rqlite/rqlite/http/service.go:633 +0x1c4
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc0001940f0, 0x4e25650, 0xc00019a8c0, 0xc000022100)
	/var/folders/tm/97rx_rf519d6lkg48r5rvt700000gn/T/tmp.zmEGcHT0/src/github.com/rqlite/rqlite/http/service.go:340 +0x458
net/http.serverHandler.ServeHTTP(0xc00019a9a0, 0x4e25650, 0xc00019a8c0, 0xc000022100)
	/usr/local/go/src/net/http/server.go:2867 +0xa3
net/http.(*conn).serve(0xc000310780, 0x4e27960, 0xc0003386c0)
	/usr/local/go/src/net/http/server.go:1932 +0x8cd
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2993 +0x39b
```
- I also notice that immediately following a restore command, I can view the size of the raft log raft.db . Within a second or two, the raft log is done being written to (so this seems to be really fast). This is the case whether the restore file size is ~2mb or ~15mb. However, the ~2mb restore file takes ~10 seconds to apply to sqlite, and the ~15mb restore file takes ~1 minute to apply to sqlite. I’m not sure but there seems to be some optimizations to make related to writing the transactions to sqlite. Restoring a ~15mb file to sqlite directly it takes about ~3 seconds. I’m not saying it should be that fast, but it seems it should be quicker.
- The other thing related to the last point (that may help), is that on startup, the process of reading and applying the transactions from raft log to the in-memory db takes quite awhile (~4m for a ~50mb db). This seems to point to something related to building the sqlite db from raft.
The last 2 points seem to point to the process of writing to sqlite (because the raft log is finished very quickly while the db is still locked for some time applying transactions to sqlite. It goes without saying but during the operations listed above, the CPU is always pegged out so I can tell something is happening, but not sure what exactly.

**Comment by otoolep** [comment] 2022-05-06 21:52
Are you prepared to supply me with your 100MB file? You could compress it first, and send to me.

**Comment by jmordica** [comment] 2022-05-06 22:40
I sure can. Even better, I’ll send you a 19mb file since it seems anything over ~15mb produces the error output above and locks the process. I’ll DM it to you via slack in a bit.

**Comment by otoolep** [comment] 2022-05-07 17:26
Thanks, I've tried the download. I think I'm seeing the same thing as you, let me dig into it more.

**Comment by otoolep** [comment] 2022-05-07 17:43
It appears to hanging in the Go layer between `rqlited` and the SQLite database i.e. https://github.com/mattn/go-sqlite3. It may be something in that layer, or a bug in the way I'm using it. Continuing to investigate.

**Comment by otoolep** [comment] 2022-05-07 17:47
I generated a stack trace of all Goroutines while the system appears hung:
```
>>>>>>> db.Execute().....calling
Calling ExecContext()..... 20201487 0
^\SIGQUIT: quit
PC=0x473041 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex()
	/home/philip/.gvm/gos/go1.17/src/runtime/sys_linux_amd64.s:519 +0x21
runtime.futexsleep(0xc000056000, 0x413bb3, 0x1e)
	/home/philip/.gvm/gos/go1.17/src/runtime/os_linux.go:44 +0x36
runtime.notesleep(0x1631350)
	/home/philip/.gvm/gos/go1.17/src/runtime/lock_futex.go:160 +0x87
runtime.mPark()
	/home/philip/.gvm/gos/go1.17/src/runtime/proc.go:1441 +0x2a
runtime.stopm()
	/home/philip/.gvm/gos/go1.17/src/runtime/proc.go:2408 +0x78
runtime.findrunnable()
	/home/philip/.gvm/gos/go1.17/src/runtime/proc.go:2984 +0x865
runtime.schedule()
	/home/philip/.gvm/gos/go1.17/src/runtime/proc.go:3367 +0x239
runtime.park_m(0xc0004824e0)
	/home/philip/.gvm/gos/go1.17/src/runtime/proc.go:3516 +0x14d
runtime.mcall()
	/home/philip/.gvm/gos/go1.17/src/runtime/asm_amd64.s:307 +0x43

goroutine 1 [chan receive, 11 minutes]:
main.main()
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/cmd/rqlited/main.go:155 +0xe72

goroutine 36 [IO wait, 11 minutes]:
internal/poll.runtime_pollWait(0x7f171d2ba7f0, 0x72)
	/home/philip/.gvm/gos/go1.17/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc0000ca280, 0xc00019a0c0, 0x0)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0000ca280)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc0000ca280)
	/home/philip/.gvm/gos/go1.17/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc0000b6138)
	/home/philip/.gvm/gos/go1.17/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc0000b6138)
	/home/philip/.gvm/gos/go1.17/src/net/tcpsock.go:262 +0x3d
github.com/rqlite/rqlite/tcp.(*Mux).Serve(0xc00042e000)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/tcp/mux.go:149 +0x142
created by main.startNodeMux
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/cmd/rqlited/main.go:287 +0x20f

goroutine 37 [chan receive, 11 minutes]:
github.com/rqlite/rqlite/tcp.(*listener).Accept(0x10)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/tcp/mux.go:260 +0x27
github.com/rqlite/rqlite/tcp.(*Layer).Accept(0xc0000a6420)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/tcp/mux.go:57 +0x22
github.com/rqlite/rqlite/store.(*Transport).Accept(0xc0000a6420)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/store/transport.go:35 +0x22
github.com/hashicorp/raft.(*NetworkTransport).listen(0xc00043e000)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/net_transport.go:491 +0x53
created by github.com/hashicorp/raft.NewNetworkTransportWithConfig
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/net_transport.go:180 +0x28f

goroutine 38 [select, 11 minutes]:
database/sql.(*DB).connectionOpener(0xc0000bb930, {0xffe798, 0xc0000b1280})
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:1196 +0x93
created by database/sql.OpenDB
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:794 +0x188

goroutine 5 [select, 11 minutes]:
database/sql.(*DB).connectionOpener(0xc00010e0d0, {0xffe798, 0xc00004a140})
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:1196 +0x93
created by database/sql.OpenDB
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:794 +0x188

goroutine 6 [select]:
github.com/hashicorp/raft.(*Raft).leaderLoop(0xc00011c000)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/raft.go:583 +0x3e5
github.com/hashicorp/raft.(*Raft).runLeader(0xc00011c000)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/raft.go:474 +0x46a
github.com/hashicorp/raft.(*Raft).run(0xc00011c000)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/raft.go:144 +0x4a
github.com/hashicorp/raft.(*raftState).goFunc.func1()
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/state.go:146 +0x62
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/state.go:144 +0x92

goroutine 7 [runnable]:
strings.TrimSpace({0xc001ca8000, 0x82d275})
	/home/philip/.gvm/gos/go1.17/src/strings/strings.go:867 +0x14b
github.com/rqlite/go-sqlite3.(*SQLiteConn).prepare(0xc00007c1e0, {0xffe7d0, 0xc00019e000}, {0xc00147a001, 0x0})
	/home/philip/repos/rqlite/pkg/mod/github.com/rqlite/go-sqlite3@v1.24.0/sqlite3.go:1865 +0xd5
github.com/rqlite/go-sqlite3.(*SQLiteConn).exec(0x7f17467ba108, {0xffe7d0, 0xc00019e000}, {0xc0029aa000, 0x0}, {0x1664180, 0x0, 0x0})
	/home/philip/repos/rqlite/pkg/mod/github.com/rqlite/go-sqlite3@v1.24.0/sqlite3.go:855 +0x99
github.com/rqlite/go-sqlite3.(*SQLiteConn).ExecContext(0xc0000c6cc0, {0xffe7d0, 0xc00019e000}, {0xc0029aa000, 0x134400f}, {0x1664180, 0x0, 0xc0001d5638})
	/home/philip/repos/rqlite/pkg/mod/github.com/rqlite/go-sqlite3@v1.24.0/sqlite3_go18.go:41 +0xbb
database/sql.ctxDriverExec({0xffe7d0, 0xc00019e000}, {0x7f171f3587b8, 0xc00007c1e0}, {0x0, 0x0}, {0xc0029aa000, 0xd0f972}, {0x1664180, 0x0, ...})
	/home/philip/.gvm/gos/go1.17/src/database/sql/ctxutil.go:31 +0x17d
database/sql.(*DB).execDC.func2()
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:1646 +0x175
database/sql.withLock({0xfee808, 0xc000112000}, 0xc0001d5830)
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:3396 +0x8c
database/sql.(*DB).execDC(0xc000042100, {0xffe7d0, 0xc00019e000}, 0xc000112000, 0xc0004a6000, {0xc0029aa000, 0x134400f}, {0x0, 0x0, 0x0})
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:1641 +0x266
database/sql.(*Conn).ExecContext(0xc0000a82a0, {0xffe7d0, 0xc00019e000}, {0xc0029aa000, 0x134400f}, {0x0, 0x0, 0x0})
	/home/philip/.gvm/gos/go1.17/src/database/sql/sql.go:1962 +0xb7
github.com/rqlite/rqlite/db.(*DB).Execute(0xc00007e050, 0xc0001ac000, 0x0)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/db/db.go:438 +0x52c
github.com/rqlite/rqlite/store.applyCommand({0xc000aca000, 0x17a6a0, 0x17a6a0}, 0x0)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/store/store.go:1633 +0x236
github.com/rqlite/rqlite/store.(*Store).Apply(0xc000438000, 0xc000297418)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/store/store.go:1141 +0x114
github.com/hashicorp/raft.(*Raft).runFSM.func1(0xc0000acda0)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/fsm.go:98 +0x235
github.com/hashicorp/raft.(*Raft).runFSM.func2({0xc00027a200, 0x1, 0xc000438000})
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/fsm.go:121 +0x48f
github.com/hashicorp/raft.(*Raft).runFSM(0xc00011c000)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/fsm.go:231 +0x35a
github.com/hashicorp/raft.(*raftState).goFunc.func1()
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/state.go:146 +0x62
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/state.go:144 +0x92

goroutine 8 [select]:
github.com/hashicorp/raft.(*Raft).runSnapshots(0xc00011c000)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/snapshot.go:71 +0x18e
github.com/hashicorp/raft.(*raftState).goFunc.func1()
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/state.go:146 +0x62
created by github.com/hashicorp/raft.(*raftState).goFunc
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/state.go:144 +0x92

goroutine 9 [select, 11 minutes]:
github.com/rqlite/rqlite/store.(*Store).observe.func1()
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/store/store.go:1265 +0xcf
created by github.com/rqlite/rqlite/store.(*Store).observe
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/store/store.go:1262 +0x10f

goroutine 10 [chan receive, 11 minutes]:
github.com/rqlite/rqlite/tcp.(*listener).Accept(0x0)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/tcp/mux.go:260 +0x27
github.com/rqlite/rqlite/tcp.(*Layer).Accept(0x0)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/tcp/mux.go:57 +0x22
github.com/rqlite/rqlite/cluster.(*Service).serve(0xc00011e0e0)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/cluster/service.go:161 +0x3e
created by github.com/rqlite/rqlite/cluster.(*Service).Open
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/cluster/service.go:98 +0x5f

goroutine 13 [IO wait, 11 minutes]:
internal/poll.runtime_pollWait(0x7f171d2ba708, 0x72)
	/home/philip/.gvm/gos/go1.17/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc00010c200, 0x203000, 0x0)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc00010c200)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_unix.go:402 +0x22c
net.(*netFD).accept(0xc00010c200)
	/home/philip/.gvm/gos/go1.17/src/net/fd_unix.go:173 +0x35
net.(*TCPListener).accept(0xc00000e258)
	/home/philip/.gvm/gos/go1.17/src/net/tcpsock_posix.go:140 +0x28
net.(*TCPListener).Accept(0xc00000e258)
	/home/philip/.gvm/gos/go1.17/src/net/tcpsock.go:262 +0x3d
net/http.(*Server).Serve(0xc0001162a0, {0xff2b60, 0xc00000e258})
	/home/philip/.gvm/gos/go1.17/src/net/http/server.go:3001 +0x394
github.com/rqlite/rqlite/http.(*Service).Start.func1()
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/http/service.go:290 +0x32
created by github.com/rqlite/rqlite/http.(*Service).Start
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/http/service.go:289 +0x285

goroutine 15 [syscall, 11 minutes]:
os/signal.signal_recv()
	/home/philip/.gvm/gos/go1.17/src/runtime/sigqueue.go:169 +0x98
os/signal.loop()
	/home/philip/.gvm/gos/go1.17/src/os/signal/signal_unix.go:24 +0x19
created by os/signal.Notify.func1.1
	/home/philip/.gvm/gos/go1.17/src/os/signal/signal.go:151 +0x2c

goroutine 50 [select]:
github.com/hashicorp/raft.emitLogStoreMetrics({0x1004a98, 0xc0000b1140}, {0xc0004b41c0, 0x2, 0x2}, 0x0, 0xc0004d60c0)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/log.go:163 +0xd4
created by github.com/hashicorp/raft.(*Raft).runLeader
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/raft.go:399 +0x3bf

goroutine 16 [select, 11 minutes]:
github.com/hashicorp/raft.(*deferError).Error(0xc0002973f0)
	/home/philip/repos/rqlite/pkg/mod/github.com/hashicorp/raft@v1.3.6/future.go:110 +0x89
github.com/rqlite/rqlite/store.(*Store).execute(0xc000438000, 0xc0000b4188)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/store/store.go:744 +0x19d
github.com/rqlite/rqlite/store.(*Store).Execute(0xc0001cfa60, 0x1)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/store/store.go:718 +0x49
github.com/rqlite/rqlite/http.(*Service).handleLoad(0xc000128000, {0xff2d70, 0xc000116380}, 0xc00010a200)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/http/service.go:597 +0x20a
github.com/rqlite/rqlite/http.(*Service).ServeHTTP(0xc000128000, {0xff2d70, 0xc000116380}, 0xc00010a200)
	/home/philip/repos/rqlite/src/github.com/rqlite/rqlite/http/service.go:329 +0x4a5
net/http.serverHandler.ServeHTTP({0xfef7d0}, {0xff2d70, 0xc000116380}, 0xc00010a200)
	/home/philip/.gvm/gos/go1.17/src/net/http/server.go:2878 +0x43b
net/http.(*conn).serve(0xc000114140, {0xffe840, 0xc00038ade0})
	/home/philip/.gvm/gos/go1.17/src/net/http/server.go:1929 +0xb08
created by net/http.(*Server).Serve
	/home/philip/.gvm/gos/go1.17/src/net/http/server.go:3033 +0x4e8

goroutine 41 [IO wait, 11 minutes]:
internal/poll.runtime_pollWait(0x7f171d2ba620, 0x72)
	/home/philip/.gvm/gos/go1.17/src/runtime/netpoll.go:229 +0x89
internal/poll.(*pollDesc).wait(0xc00010c280, 0xc000108821, 0x0)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_poll_runtime.go:84 +0x32
internal/poll.(*pollDesc).waitRead(...)
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Read(0xc00010c280, {0xc000108821, 0x1, 0x1})
	/home/philip/.gvm/gos/go1.17/src/internal/poll/fd_unix.go:167 +0x25a
net.(*netFD).Read(0xc00010c280, {0xc000108821, 0x0, 0x0})
	/home/philip/.gvm/gos/go1.17/src/net/fd_posix.go:56 +0x29
net.(*conn).Read(0xc0000100a8, {0xc000108821, 0x0, 0xb991bc})
	/home/philip/.gvm/gos/go1.17/src/net/net.go:183 +0x45
net/http.(*connReader).backgroundRead(0xc000108810)
	/home/philip/.gvm/gos/go1.17/src/net/http/server.go:672 +0x3f
created by net/http.(*connReader).startBackgroundRead
	/home/philip/.gvm/gos/go1.17/src/net/http/server.go:668 +0xcf

rax    0xca
rbx    0x0
rcx    0x473043
rdx    0x0
rdi    0x1631350
rsi    0x80
rbp    0x7ffff1bc04a8
rsp    0x7ffff1bc0460
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x93
r13    0xd5f6c0
r14    0x1630c00
r15    0x0
rip    0x473041
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
```

I think this is the code that's churning away, and not returning when we hope:
```
goroutine 7 [runnable]:
strings.TrimSpace({0xc001ca8000, 0x82d275})
	/home/philip/.gvm/gos/go1.17/src/strings/strings.go:867 +0x14b
github.com/rqlite/go-sqlite3.(*SQLiteConn).prepare(0xc00007c1e0, {0xffe7d0, 0xc00019e000}, {0xc00147a001, 0x0})
	/home/philip/repos/rqlite/pkg/mod/github.com/rqlite/go-sqlite3@v1.24.0/sqlite3.go:1865 +0xd5
```

**Comment by otoolep** [comment] 2022-05-07 17:52
I suspect the `for` loop here: https://github.com/mattn/go-sqlite3/blob/master/sqlite3.go#L850 is not exiting. Either we're just not waiting long enough, or we've brought out a bug in that code.

**Comment by otoolep** [comment] 2022-05-07 18:12
It worked, I just had to wait 13 mins.
```
$ time curl -XPOST localhost:4001/db/load -H "Content-type: text/plain" --data-binary @av_autoprovisionvalues.sql
{"results":[{"last_insert_id":1253097,"rows_affected":1}]}
real	13m52.401s
user	0m0.058s
sys	0m0.035s
```
I agree this is kinda slow, there might be some way of speeding up the code.

The panic you hit is not the cause of the slowdown, but I do need to fix it too.

**Comment by jmordica** [comment] 2022-05-07 18:16
I’m suspecting whatever is causing this to be so slow is also somewhat related to the amount of time it takes for the sqlite db to build from the raft log. I believe it is somewhere around 30 seconds for a 2mb size (which seems like a lot)?

**Comment by otoolep** [comment] 2022-05-08 14:13
I've asked a question on the upstream repo.

**Comment by otoolep** [comment] 2022-05-09 16:45
I think I'll be able to improve this a lot, if I just add an API that allows you to load an SQLite file into the API (as opposed to SQL text). If I built this API, would you use it? API would be of the form:
```bash
curl -XPOST localhost:4001/db/load?fmt=binary -H "Content-type: text/plain" --data-binary @restore.db
```
Note the addtion of the URL param `fmt`. `restore.db` would be an actual SQLite file. This shouldn't take more than a few seconds, as the SQLite file would be installed directly into rqlite. Any existing data would be erased.

**Comment by jmordica** [comment] 2022-05-09 17:01
This would work and yes I would use it.

So in the future, if importing a sql text file, we would just need to wait (even if the file has a `BEGIN TRANSACTION;` and `COMMIT;` correct?

**Comment by otoolep** [comment] 2022-05-09 17:56
>So in the future, if importing a sql text file, we would just need to wait (even if the file has a BEGIN TRANSACTION; and COMMIT; correct?

Yes, I would leave that option in place, and update the docs to say it can be slow. If folks needs a faster version, just load the SQLite file directly (assuming the new API is faster).

>and what about startup time when rqlite has to build the sqlite db from raft? Any optimizations to be found there?

The new functionality I plan to add will be used by *both* the new API option *and* rebuilding from Raft at startup, so if this works, it should solve both problems.

**Comment by otoolep** [comment] 2022-05-09 18:01
I plan to work on this quite soon (within days). I *think* it will be straightforward to implement.

**Comment by otoolep** [comment] 2022-05-10 02:44
@jmordica -- are you able to build HEAD? Or do you need a release to test out the fix?

**Comment by otoolep** [comment] 2022-05-10 03:16
If you build head, you'll have access to the new API. It's documented here:

https://github.com/rqlite/rqlite/blob/master/DOC/RESTORE_FROM_SQLITE.md#http

**Comment by otoolep** [comment] 2022-05-10 03:16
Using the new API, it takes my machine less than 5 seconds to load the SQLite database. Restarting the single node takes about the same length of time, and the data is rebuilt without any issues.

**Comment by jmordica** [comment] 2022-05-10 04:43
Sweet! Confirmed here. ⚡ fast

**Comment by otoolep** [comment] 2022-05-10 13:10
Great, I'll make a release shortly, it will be 7.4.0.

**Comment by otoolep** [comment] 2022-05-10 15:20
Considering this issue fixed on master.

**Closed by otoolep** 2022-05-10 15:20 UTC

**Comment by otoolep** [comment] 2022-05-11 00:00
7.4.0 has been released.
