### ISSUE TITLE
rqlite may experience duplicate data insertion in case of network packet loss

### ISSUE THREAD

**Issue by huanghj78** [rqlite/rqlite#1628] opened 2024-01-25 16:35 UTC
**What version are you running?**
rqlited 8 linux amd64 go1.21.0 sqlite3.44.0 
**Are you using Docker or Kubernetes to run your system?**
Docker
**Are you running a single node or a cluster?**
a cluster
version: "3.6"
services:
  node1:
    image: rqlited:latest
    volumes:
      - node1-data:/rqlite-data
    expose:
      - 2379
      - 2380
    networks:
      rqlite:
        ipv4_address: 172.16.237.100
    command:
      - /usr/local/bin/rqlited
      - --node-id=1
      - --http-addr
      -  172.16.237.100:2379
      - --raft-addr
      - 172.16.237.100:2380
      - /rqlite-data

  node2:
    image: rqlited:latest
    volumes:
      - node2-data:/rqlite-data
    networks:
      rqlite:
        ipv4_address: 172.16.237.101
    expose:
      - 2379
      - 2380
    command:
      - /usr/local/bin/rqlited
      - --node-id=2
      - --http-addr
      -  172.16.237.101:2379
      - --raft-addr
      -  172.16.237.101:2380
      - --join 
      -  172.16.237.100:2380
      - /rqlite-data

  node3:
    image: rqlited:latest
    volumes:
      - node3-data:/rqlite-data
    networks:
      rqlite:
        ipv4_address: 172.16.237.102
    expose:
      - 2379
      - 2380
    command:
      - /usr/local/bin/rqlited
      - --node-id=3
      - --http-addr
      -  172.16.237.102:2379
      - --raft-addr
      -  172.16.237.102:2380
      - --join 
      -  172.16.237.100:2380
      - /rqlite-data

volumes:
  node1-data:
  node2-data:
  node3-data:

networks:
  rqlite:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.237.0/24

**What did you do?**
(1) I use chaosblade to inject network loss fault into node2's raft port and then I use rqlite client to execute SQL `insert into t values(1);` to insert one column into an empty table `t`.  
(2) Due to the network loss fault, the rqlite client is timeout and quit.
**What did you expect to happen?**
After remove the fault, since the rqlite client has been timeout and quit, if I execute SQL `select * from t;`, there will be no column.
**What happened instead?**
I get more than one column.
<img width="939" alt="image" src="https://github.com/rqlite/rqlite/assets/55356089/651d93ae-5c14-438b-a1cd-1b8a8e293e52">

**Please include the Status, Nodes, and Expvar output from each node (or at least the Leader!)**

See https://github.com/rqlite/rqlite/blob/master/DOC/DIAGNOSTICS.md

**Comment by otoolep** [comment] 2024-01-25 17:55
Oh, sorry, I misintrepreted your report. I see the extra data now. Thank you.

This sounds like the same issue being here: https://github.com/rqlite/rqlite/pull/1624 -- this PR suggests that I change how rqlite retries commands sent over the network. I wonder if you're hitting the same issue?

**Comment by otoolep** [comment] 2024-01-25 17:56
When you're in this state, I'd like to see the output of `http://<host>/debug/vars` from each node.

**Comment by otoolep** [comment] 2024-01-26 03:50
Try 8.18 and see if you see the issues.

**Comment by huanghj78** [comment] 2024-01-26 05:12
Thank you for your reply! I tried 8.18 and found that there will be no issue with duplicate data insertion. 
However, I have a new question. When I tried to insert data, I found that the client would have different error hints in two situations and the server would have different responses.
(1) When I create a table and insert data, if the client timeout due to the network loss, the client reports "ERR! factory is not able to fill the pool: dial tcp 172.16.237.102:2380: i/o timeout" and **no data is inserted**.
(2) After (1), I try to insert data again, if the client timeout due to the network loss, the client reports "ERR! read protobuf length: read tcp 172.16.237.100:52382->172.16.237.102:2380: i/o timeout" and **there is one column inserted**.
![image](https://github.com/rqlite/rqlite/assets/55356089/40c25016-772d-42c1-be7c-79adc1cfd669)
rqlite has inconsistent reactions to the same fault. I wonder if this is a bug?

**Comment by otoolep** [comment] 2024-01-26 14:25
So I don't think it's necessarily a bug. When a node forwards a INSERT request to another node it's a multi-step process (see the code [here](https://github.com/rqlite/rqlite/blob/v8.18.0/cluster/client.go#L133)). 

Presumably your test is injecting network faults at random. So your testing is simply interrupting that network request at different points. In the first case it interrupted the request before the node could make the initial connection to the other node. In the second example it interrupted the request after the node had successfully sent the INSERT to the other node, but before it could read back the response from the other node.

Does this sound reasonable?

If you are seeing the above sequence *every time* then it's more likely to be bug. But if it varies from run-to-run, I don't think it's bug. I do think the error messages need improving though.

**Comment by otoolep** [comment] 2024-01-26 14:47
Looks like you might be building your own code. I just made a change to master to improve the error messages, you may wish to build the latest code.

**Comment by huanghj78** [comment] 2024-01-27 06:05
Thank you for your reply! I have tried more than 10 times and each time I see the same sequence, so I think it is highly likely to occur stably. Specifically, I inject network loss fault into the 2 follower nodes' raft port and execute the above sequence.

**Comment by otoolep** [comment] 2024-01-27 14:03
I am not familiar with chaosblade. Can you show me how you invoke it, so I can reproduce the issue?

**Comment by huanghj78** [comment] 2024-01-27 15:18
Sure~ I deploy  a 3-node cluster by docker compose.  The content of docker-compose file is shown above.
(1) Download  [chaosblade v1.3.0]( https://github.com/chaosblade-io/chaosblade/releases/download/v1.3.0/chaosblade-1.3.0-linux-amd64.tar.gz) and decompress the file to obtain the binary files `blade`
(2) use command `blade create docker network loss --percent 100 --timeout $duration --interface eth0 --local-port 2380 --container-name rqlite-node2-1` and `blade create docker network loss --percent 100 --timeout $duration --interface eth0 --local-port 2380 --container-name rqlite-node3-1` to inject network loss fault into the raft port(2380) of node2 and node3(both are followers)
Thank you for trying!

**Comment by huanghj78** [comment] 2024-02-04 02:02
@otoolep hi~ May I ask if you have any conclusions

**Comment by otoolep** [comment] 2024-02-04 02:42
Unfortunately I have not had a chance to look at this yet. I'll see if I can get to it soon.

**Comment by otoolep** [comment] 2024-02-04 03:56
So I thought about this a bit more.

On the first attempt the node doesn't even manage to connect to the other node (the dial fails), so it gives up. But because it couldn't connect at all, no INSERT can ever be sent to the other node. You can see this -- the SELECT returns no result.

Then you try again, and what seems to happen is that the node gets another connection from the pool, but one that is already connected to the other node, so no dialing is needed. Then it sends the INSERT to that node, and attempts to read back the response. Then, presumably due to the network faults you are injecting, fails to read the response. But whatever type of network fault you're injecting doesn't stop the INSERT getting to the other node. 

It also seems that the cluster is still  working OK because the INSERT is committed to the database, which means that a quorum of nodes remains in contact with each other.

Another way of thinking about this issue is to ask: what do you expect should happen? The output you show above shows the node failing to read a response from the node that it sent the INSERT too. However that doesn't mean the other node didn't receive -- and process -- the response. You may be expecting that to fail to read the response means the other node didn't get the INSERT, but that is not necessarily true.

Now, what would be a bug, would be the following: rhe node reports that it can't *send* the INSERT to the other node, but the INSERT still happens. That would be a bug. But that is not what is happening here. What is happening is that the node is reporting that it doesn't know what happened -- the other node may or may not have received the INSERT -- but the node can't tell because it failed to read any response from the other node. And, as it turns out, the other node did receive the INSERT, and was able to apply it to the cluster i.e. quorum was reached.

I think this bug should probably be closed, any clustered system, even 100% right, can suffer from this issue as far as I can see. You're basically experiencing [The Two Generals Problem](https://en.wikipedia.org/wiki/Two_Generals%27_Problem).

**Comment by otoolep** [comment] 2024-02-04 14:38
I've improved an message that is returned when a query on a remote node fails, for the reasons I discussed above. This should make it clearer to end users what has happened in the case of failure. Otherwise I have no plans to do any more work here, because this is simply a fundamental limit of distributed systems, for the reasons outlined above.

That said, I'm keen to be proven wrong, but I don't see it right now. Feel free to re-open if you have more evidence or reasoning.

**Closed** 2024-02-04 14:41 UTC
